//! expectations — the DECLARED-LAWS gate: each module's DISTANCE from its declared
//! algebra (`Distance::of`), red until discovery earns every declared law.
//!
//! GENERATED by genesis from the `credit-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! RED BY DESIGN until the meaning holes are filled: the failure message IS the
//! worklist ("MISSING: ..."). Surprises (discovered, never declared) do not fail —
//! ratify them into the declaration or refute the operator that produced them.

use boundary_spec::discover::expect::Distance;

use credit_app::ops::meter_ops::Meter;

/// `meter` declares 3 law(s); the distance report names any that discovery has
/// not (yet) found true of the meaning.
#[test]
fn meter_meets_its_declared_expectations() {
    let distance = Distance::of::<Meter>();
    assert!(distance.is_met(), "{}", distance.render());
}
