//! probes — the edge-probe half of the contract: the build shim proves every edge HAS an
//! `impl Probed`; this file is where the probes RUN in CI.
//!
//! GENERATED by genesis for `credit-app` as a STUB: genesis emits no edges, because an edge (a
//! Construction's parse, a Branch's classification, a Guarded edge's witness) is meaning, not
//! structure. Mint the domain's edges on the boundary surface and probe them here — the
//! downstream-fixture's `tests/probes.rs` is the reference shape (entry parse, branch, guarded
//! chain, driven end to end).

// MEANING (filled): this system's edges are the two entry constructions (`Credits::new`,
// `Receipt::new`) and the saturating interior re-entry (`mint`, observed through the
// operators) — probed below at the validity rules' load-bearing points.

use credit_app::billing::Receipt;
use credit_app::meter::Credits;

/// The entry edge is "parse, don't validate": both edges of `0..=20` are admitted, both
/// neighbours outside are refused, and the raw value round-trips unchanged.
#[test]
fn credits_construction_is_parse_dont_validate() {
    for valid in [0, 1, 19, 20] {
        let credits = Credits::new(valid).expect("in range");
        assert_eq!(credits.get(), valid, "construction must not renormalise");
    }
    assert!(Credits::new(-1).is_none(), "below the floor");
    assert!(Credits::new(21).is_none(), "above the cap");
}

/// The receipt rule is literal non-emptiness: the empty reference is refused, the shortest
/// non-empty one is admitted, and the reference round-trips unchanged.
#[test]
fn receipt_construction_refuses_only_the_empty_reference() {
    assert!(Receipt::new(String::new()).is_none());
    let receipt = Receipt::new("r".to_string()).expect("non-empty");
    assert_eq!(receipt.get(), "r");
}

/// The interior re-entry SATURATES at both edges, observed through the operators: granting
/// onto a nearly-full meter clamps to the cap, and charging more than the balance clamps to
/// empty — a computation can overshoot, a balance cannot.
#[test]
fn the_operators_saturate_at_the_rules_edges() {
    let credits = |n: i64| Credits::new(n).expect("valid balance");
    assert_eq!(credits(15).grant(credits(10)).get(), 20, "cap saturation");
    assert_eq!(
        credits(0).grant(credits(7)).get(),
        7,
        "identity at the floor"
    );
    let receipt = Receipt::new("xxxxx".to_string()).expect("non-empty");
    assert_eq!(credits(3).charge(receipt).get(), 0, "floor saturation");
    assert_eq!(
        credits(4).renew(credits(9)).get(),
        9,
        "renewal replaces — the later operand wins"
    );
}
