//! seams — the DECLARED seam obligations, one test per seam.
//!
//! GENERATED by genesis for `credit-app`. A seam names what a module split must preserve:
//! a `transport` seam shares a sort that is the SAME type on both sides (preserved by
//! construction — genesis defines each value object exactly once); a `transform` seam
//! carries a conversion that must be a HOMOMORPHISM, and that check is a meaning hole.

/// TRANSPORT seam `meter -- billing` on `Credits`: both modules must use the one `Credits` type, so the
/// algebra crosses the seam unchanged. Discharged by construction — `Credits` is defined once,
/// in `credit_app::meter` — and witnessed here by a compile-time identity: if the sides ever
/// diverge into two types, this stops compiling.
#[test]
fn seam_meter_billing_transport_on_credits() {
    let _witness: fn(credit_app::meter::Credits) -> credit_app::meter::Credits = |value| value;
}
