//! `billing`'s strict value-object surface — a DOOR by structure: its operator methods
//! front the interior workshop, which derives this file BOUNDARY (the tier-1 grammar).
//!
//! GENERATED by genesis from the `credit-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! The newtypes below are STRUCTURE; their validity rules are carried VERBATIM from the
//! declaration as meaning holes. Operator methods delegate inward — the tier-1 grammar
//! (no free functions, no public fields, no I/O) is enforced by this crate's build.rs.

use crate::meter::Credits;
use boundary_spec::boundary::Shaped;

/// `Receipt` — `String` refined by a declared validity rule.
///
/// VALIDITY (declared, carried verbatim — never generated): "non-empty"
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Receipt(String);

impl Receipt {
    /// Parse, don't validate: `Some` iff `raw` satisfies the declared rule.
    pub fn new(raw: String) -> Option<Receipt> {
        // MEANING (filled): the declared rule is literal — a receipt is any non-empty
        // reference string; there is nothing to charge against a blank one.
        (!raw.is_empty()).then_some(Receipt(raw))
    }

    /// The raw value — the sanctioned exit hatch.
    pub fn get(&self) -> String {
        self.0.clone()
    }

    /// The interior's way back into validity from a raw computation. Choosing the
    /// discipline (clamp? reject? panic?) is domain meaning, not structure.
    pub(crate) fn mint(raw: String) -> Receipt {
        // MEANING (filled): a computed reference that comes out blank re-enters validity as
        // the placeholder receipt — the billing analogue of the meter's clamp.
        if raw.is_empty() {
            Receipt("-".to_string())
        } else {
            Receipt(raw)
        }
    }
}

/// The probe/grid surface: discovery can only refute what this grid reaches, so step
/// the perturbations toward the validity rule's load-bearing points.
impl Shaped for Receipt {
    fn inhabitant() -> Self {
        // MEANING (filled): the shortest valid receipt — one step from the "non-empty"
        // edge, so the grid starts at the rule's load-bearing point.
        Receipt("r".to_string())
    }
    fn perturbation_classes(&self) -> Vec<Vec<Self>> {
        // MEANING (filled): one class growing the reference (longer receipts charge more),
        // one swapping it for a different same-length reference — both through `mint`, so
        // every neighbour is valid. Growth is capped so the closure stays finite-ish and
        // the grid covers several charge magnitudes.
        let grown = if self.0.len() < 4 {
            format!("{}r", self.0)
        } else {
            self.0.clone()
        };
        vec![
            vec![Receipt::mint(grown)],
            vec![Receipt::mint("x".repeat(self.0.len()))],
        ]
    }
}

boundary_spec::value_object!(Receipt);

// ===== operator methods — mechanical delegation; the meaning lives in the
// interior workshop =====

impl Credits {
    /// `charge` — declared `charge(Credits, Receipt) -> Credits`, delegated to the interior
    /// (`crate::billing_internal::charge`), where its MEANING hole lives.
    pub fn charge(self, b: Receipt) -> Credits {
        crate::billing_internal::charge(self, b)
    }
}
