//! The workshop `billing`'s boundary delegates to — not pub-reachable, deriving INTERIOR
//! (the tier-2 inward rule holds: nothing here returns a raw primitive).
//!
//! GENERATED by genesis from the `credit-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! Every body below is THE meaning hole for its operator. The interior is free — raw
//! representation arithmetic, any style — but the only way back out is a value object's
//! `mint`, so a quantity cannot leave un-validated.

use crate::billing::Receipt;
use crate::meter::Credits;

/// `charge` — the operator's interior.
/// No laws were declared for it — whatever discovery finds is the spec.
pub(crate) fn charge(a: Credits, b: Receipt) -> Credits {
    // MEANING (filled): a receipt costs one credit per character of its reference, and the
    // balance saturates at empty (`mint` clamps) — billing can never drive a meter negative.
    Credits::mint(a.get() - b.get().len() as i64)
}
