//! A discovered-law / report layer (exempt from the inward rule).
//!
//! gates — THE PIPELINE IS A LOCK, the consumer form: this crate's CI is a declaration.
//!
//! GENERATED by genesis for `credit-app`. `spec/gates.spec` (the promises) and
//! `.github/workflows/ci.yml` (the execution) are BOTH rendered from the declaration
//! below and drift-gated byte for byte (`tests/gates.rs`), so the pipeline cannot be
//! hand-edited into silent decay — the motivating bug class upstream was a hand-written
//! workflow that quietly tested the wrong scope for its whole life. Regenerate with
//! `cargo run --example freeze_gates` and ratify the diff.

use boundary_spec::discover::gates::Pipeline;

/// The pipeline declaration, as a TYPESTATE — the crate's CI surface (every public
/// callable hangs off a typestate; this crate's own enforcement shim holds this file to
/// that rule too).
pub struct Ci;

impl Ci {
    /// This crate's pipeline: the STARTER declaration (format, lint, test — every
    /// change), pinned to the toolchain the upstream library is tested against. Outgrow
    /// it by replacing this call with a hand-declared `Pipeline { .. }` — per-diff
    /// mutation and weekly gates render too, and the locks drift-gate whichever
    /// declaration stands.
    pub fn pipeline() -> Pipeline {
        Pipeline::starter()
    }
}
