//! The crate's trusted floor: the module roster, and nothing else. KERNEL is a
//! REGISTRATION (this crate's build.rs names it), never an assertion in a file.
//!
//! GENERATED by genesis from the `credit-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! # credit-app — a crate whose layout was DERIVED from one declaration
//!
//! Everything structural in this tree — the tiered layout, the operator plumbing,
//! the lock loop — was emitted by `genesis` from a single `system! { ... }` declaration
//! that fits in a context window. The declaration→files translation was mechanical, so
//! reviewing THIS crate means reviewing meaning, not transcription.
//!
//! ## The module map
//!
//! * [`meter`] (BOUNDARY) — value-object surface; `meter_internal` (INTERIOR, private) —
//!   the workshop its operators delegate to, where the meaning holes live.
//! * [`billing`] (BOUNDARY) — value-object surface; `billing_internal` (INTERIOR, private) —
//!   the workshop its operators delegate to, where the meaning holes live.
//! * [`ops`] (ALGEBRA) — each module's operators as an `#[algebra]` theory; the declared
//!   expectations ride the attribute, and discovery must re-earn them.
//! * [`system`] (ALGEBRA) — the COMPILED `system!` graph: the module registry (the graph
//!   IS the registry the freeze loop reads) and the declared seams with their checkers.
//! * [`gates`] (ALGEBRA) — the pipeline as a declaration: `spec/gates.spec` and the CI
//!   workflow are BOTH its renders, drift-gated (`cargo run --example freeze_gates`).
//! * `spec/` — TARGET locks: the DECLARED laws (and the declared seam graph) in the exact
//!   lock format, committed RED on purpose. The drift gate stays red until discovery
//!   matches the declaration.
//!
//! ## The runbook — from generated skeleton to ratified system
//!
//! 1. `grep -rn "MEANING:" src tests` — the complete list of holes: validity
//!    predicates, interior operator bodies, constants, grid shapes, edge probes.
//! 2. First build: `BLESS_CREDIT_APP_QUALIFY=1 cargo build` — mints `spec/qualify.spec`, which the
//!    enforcement shim (`build.rs`) drift-gates from then on.
//! 3. `cargo test` — the expectations gate names each module's DISTANCE from its
//!    declaration, and the freeze gate holds the LIVE discovered spec (module laws and
//!    the seam graph) against the TARGET locks; red means the meaning does not yet earn
//!    the declaration.
//! 4. `cargo run --example freeze` — regenerate the locks from discovery and read the
//!    diff against the targets. That diff IS the review: ratify it, or fix the meaning.

pub mod billing;
pub mod gates;
pub mod meter;
pub mod ops;
pub mod system;

mod billing_internal;
mod meter_internal;
