//! Tier: INTERIOR — the workshop `meter`'s boundary delegates to (the tier-2 inward
//! rule holds: nothing here returns a raw primitive).
//!
//! GENERATED by genesis from the `credit-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! Every body below is THE meaning hole for its operator. The interior is free — raw
//! representation arithmetic, any style — but the only way back out is a value object's
//! `mint`, so a quantity cannot leave un-validated.

use crate::meter::Credits;

/// `grant` — the operator's interior.
/// Declared expectations to honour (discovery must re-earn them): commutative(grant); identity(grant, zero).
pub(crate) fn grant(a: Credits, b: Credits) -> Credits {
    // MEANING (filled): granting POOLS two balances, saturating at the cap (`mint` clamps).
    // Addition is symmetric (the declared commutativity), and pooling with an empty meter
    // changes nothing (the declared identity with `zero`).
    Credits::mint(a.get() + b.get())
}

/// `renew` — the operator's interior.
/// Declared expectations to honour (discovery must re-earn them): bias_later(renew).
pub(crate) fn renew(a: Credits, b: Credits) -> Credits {
    // MEANING (filled): a renewal REPLACES the balance with the newly purchased one — the
    // later operand wins outright (the declared bias), it never tops up.
    let _ = a;
    b
}
