//! Tier: BOUNDARY — `meter`'s strict value-object surface (the tier-1 grammar).
//!
//! GENERATED by genesis from the `credit-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! The newtypes below are STRUCTURE; their validity rules are carried VERBATIM from the
//! declaration as meaning holes. Operator methods delegate inward — the tier-1 grammar
//! (no free functions, no public fields, no I/O) is enforced by this crate's build.rs.

use boundary_spec::boundary::Shaped;

/// `Credits` — `i64` refined by a declared validity rule.
///
/// VALIDITY (declared, carried verbatim — never generated): "0..=20"
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Credits(i64);

impl Credits {
    /// Parse, don't validate: `Some` iff `raw` satisfies the declared rule.
    pub fn new(raw: i64) -> Option<Credits> {
        // MEANING (filled): the declared rule is literal — a balance is a whole number of
        // credits between empty and the cap, inclusive.
        (0..=20).contains(&raw).then(|| Credits(raw))
    }

    /// The raw value — the sanctioned exit hatch.
    pub fn get(&self) -> i64 {
        self.0.clone()
    }

    /// The interior's way back into validity from a raw computation. Choosing the
    /// discipline (clamp? reject? panic?) is domain meaning, not structure.
    pub(crate) fn mint(raw: i64) -> Credits {
        // MEANING (filled): the meter SATURATES — a computation can overshoot the cap
        // (granting onto a full meter) or undershoot zero (charging an empty one), and the
        // balance clamps to the valid range rather than rejecting or panicking.
        Credits(raw.clamp(0, 20))
    }
}

/// The probe/grid surface: discovery can only refute what this grid reaches, so step
/// the perturbations toward the validity rule's load-bearing points.
impl Shaped for Credits {
    fn inhabitant() -> Self {
        // MEANING (filled): a meter starts empty — and zero is also `grant`'s declared
        // identity, so the grid pivots on the rule's most load-bearing point.
        Credits(0)
    }
    fn perturbation_classes(&self) -> Vec<Vec<Self>> {
        // MEANING (filled): one class stepping up toward the cap, one stepping down toward
        // empty — both through `mint`, so every neighbour is valid and the closure
        // (`shadow_grid`) reaches the entire 0..=20 range including both edges.
        vec![
            vec![Credits::mint(self.0 + 1), Credits::mint(20)],
            vec![Credits::mint(self.0 - 1), Credits::mint(0)],
        ]
    }
}

boundary_spec::value_object!(Credits);

// ===== operator methods — mechanical delegation; the meaning lives in the
// interior workshop =====

impl Credits {
    /// `grant` — declared `grant(Credits, Credits) -> Credits`, delegated to the interior
    /// (`crate::meter_internal::grant`), where its MEANING hole lives.
    ///
    /// Declared expectations (the target lock restates them): commutative(grant); identity(grant, zero).
    pub fn grant(self, b: Credits) -> Credits {
        crate::meter_internal::grant(self, b)
    }

    /// `renew` — declared `renew(Credits, Credits) -> Credits`, delegated to the interior
    /// (`crate::meter_internal::renew`), where its MEANING hole lives.
    ///
    /// Declared expectations (the target lock restates them): bias_later(renew).
    pub fn renew(self, b: Credits) -> Credits {
        crate::meter_internal::renew(self, b)
    }
}
