//! The discovered-law layer: each declared module's operators, as the theory
//! `#[algebra]` synthesises from ordinary function signatures.
//!
//! GENERATED by genesis from the `credit-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! Nothing about the algebras is asserted here. The `expects(...)` attribute argument
//! carries the DECLARED expectations through AS WRITTEN in the declaration; discovery
//! must re-earn them by running these functions, and the committed `spec/*.spec` target
//! locks stay red until it does.

use boundary_spec::algebra;

/// `meter`'s operator surface for discovery: the theory (`Meter`, named "meter") is what
/// `#[algebra]` reads off the signatures below.
#[algebra(
    Meter,
    "meter",
    expects(commutative(grant), identity(grant, zero), bias_later(renew))
)]
pub mod meter_ops {
    use crate::meter::Credits;

    /// The declared constant `zero` — a MEANING hole: the witness the declared laws name.
    pub fn zero() -> Credits {
        // MEANING (filled): the empty meter — `grant`'s declared identity witness.
        Credits::new(0).expect("0 credits is a valid balance")
    }

    /// `grant` — mechanical delegation to the boundary surface.
    pub fn grant(a: Credits, b: Credits) -> Credits {
        a.grant(b)
    }

    /// `renew` — mechanical delegation to the boundary surface.
    pub fn renew(a: Credits, b: Credits) -> Credits {
        a.renew(b)
    }
}

/// `billing`'s operator surface for discovery: the theory (`Billing`, named "billing") is what
/// `#[algebra]` reads off the signatures below.
#[algebra(Billing, "billing")]
pub mod billing_ops {
    use crate::billing::Receipt;
    use crate::meter::Credits;

    /// `charge` — mechanical delegation to the boundary surface.
    pub fn charge(a: Credits, b: Receipt) -> Credits {
        a.charge(b)
    }
}
