//! Tier: ALGEBRA — the compiled `system!` graph: the application-level spec as a checked artifact.
//!
//! GENERATED by genesis from the `credit-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! The graph IS the registry: `modules()` is the list the freeze loop records and the
//! drift gate checks (a module cannot silently fall out of it), and the rendered graph
//! — modules, seams, each seam's obligation and status — freezes into the committed
//! `spec/*.system.spec` lock. Declared transport seams are discharged BY CONSTRUCTION:
//! each shared value object is defined exactly once, and the `system!` macro emits the
//! compile-time witness that keeps that true.

use crate::meter::Credits;
use crate::ops::billing_ops::Billing;
use crate::ops::meter_ops::Meter;

/// The system marker — `SystemReport::of::<CreditApp>()` is the graph the lock freezes.
pub struct CreditApp;

boundary_spec::system! {
    CreditApp : "credit-app",
    modules {
        Meter;
        Billing;
    }
    seams {
        Meter -- Billing : transport on Credits by construction;
    }
}
