//! Tier: ALGEBRA — a discovered-law / report layer (exempt from the inward rule).
//!
//! freeze — the discovered spec is a committed, diffable artifact (a behaviour lock).
//!
//! Discovery is a pure function of the boundary, so the expensive enumeration is run ONCE and its
//! output FROZEN into a committed file per theory under `spec/`. The staleness gate (`check_fresh`)
//! re-derives the live spec and compares it to the committed text: a match means the code still
//! means what was ratified; a mismatch is a build error whose fix is to regenerate
//! (`cargo run --example freeze_spec`) and ratify the diff in review. So the committed spec file,
//! read in a pull request's diff, IS the ratification — the one human act discovery cannot perform.

use std::path::PathBuf;

use super::{all_specs, Spec};

/// The committed lock file for a theory, under `spec/` (the theory name slugified).
pub fn lock_path(theory: &str) -> PathBuf {
    let slug: String = theory
        .chars()
        .map(|c| if c == ' ' { '-' } else { c })
        .collect();
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("spec")
        .join(format!("{slug}.spec"))
}

/// The canonical text of a discovered spec — deterministic, human-readable, diffable.
pub fn render(spec: &Spec) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# discovered spec: {} — generated by `cargo run --example freeze_spec`; ratify changes.\n\n",
        spec.theory
    ));
    for law in &spec.laws {
        out.push_str(&format!("- {}\n      {}\n", law.prose(), law.equation()));
    }
    out.push('\n');
    out.push_str(&format!(
        "# {} further consequence equalities (implied by the laws above)\n",
        spec.consequences
    ));
    let coverage = if spec.uncovered_ops.is_empty() {
        "none — every operator participates in a law".to_string()
    } else {
        spec.uncovered_ops.join(", ")
    };
    out.push_str(&format!(
        "# operators in no law (where the spec is silent): {coverage}\n"
    ));
    out
}

/// Check every theory's LIVE spec against its committed lock. On success returns the theory names
/// verified fresh; on drift returns the names that no longer match (the fix is to regenerate and
/// ratify the diff).
pub fn check_fresh() -> Result<Vec<&'static str>, Vec<String>> {
    let mut fresh = Vec::new();
    let mut stale = Vec::new();
    for spec in all_specs() {
        let committed = std::fs::read_to_string(lock_path(spec.theory)).unwrap_or_default();
        if committed == render(&spec) {
            fresh.push(spec.theory);
        } else {
            stale.push(spec.theory.to_string());
        }
    }
    if stale.is_empty() {
        Ok(fresh)
    } else {
        Err(stale)
    }
}

#[cfg(test)]
mod tests {
    /// The committed spec locks are FRESH: every theory's live discovered spec matches what was
    /// frozen and ratified. A drift (an operator changed behaviour, the engine changed, a domain was
    /// edited) fails here — regenerate with `cargo run --example freeze_spec` and ratify the diff.
    #[test]
    fn the_committed_specs_are_fresh() {
        match super::check_fresh() {
            // all three theories' committed locks match their live discovered spec.
            Ok(fresh) => assert_eq!(
                fresh,
                vec!["interpreter arithmetic", "router", "date calculus"]
            ),
            Err(stale) => panic!(
                "discovered spec drifted from the committed lock for: {}. \
                 Run `cargo run --example freeze_spec` and ratify the diff.",
                stale.join(", ")
            ),
        }
    }
}
