//! Tier: ALGEBRA — a discovered-law / report layer (exempt from the inward rule).
//!
//! freeze — the discovered spec is a committed, diffable artifact (a behaviour lock).
//!
//! Discovery is a pure function of the boundary, so the expensive enumeration is run ONCE and its
//! output FROZEN into a committed file per theory under `spec/`. The staleness gate (`Spec::check_all_fresh`)
//! re-derives the live spec and compares it to the committed text: a match means the code still
//! means what was ratified; a mismatch is a build error whose fix is to regenerate
//! (`cargo run --example freeze_spec`) and ratify the diff in review. So the committed spec file,
//! read in a pull request's diff, IS the ratification — the one human act discovery cannot perform.
//!
//! The freeze/drift mechanics (compare live text to a committed file; write the regeneration) are
//! the domain-agnostic `spec-lock` crate; this module is the thin adapter that knows what THIS
//! repo's artifacts are — where a theory's lock lives (`lock_path`) and how a `Spec` renders
//! (`render`). See `docs/ci-discipline.md` for the whole discipline.

use std::path::PathBuf;

use spec_lock::Lock;

use super::{all_specs, Spec};

/// The committed lock file for a theory, under `spec/` (the theory name slugified).
fn lock_path(theory: &str) -> PathBuf {
    let slug: String = theory
        .chars()
        .map(|c| if c == ' ' { '-' } else { c })
        .collect();
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("spec")
        .join(format!("{slug}.spec"))
}

/// The canonical text of a discovered spec — deterministic, human-readable, diffable.
fn render(spec: &Spec) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# discovered spec: {} — generated by `cargo run --example freeze_spec`; ratify changes.\n\n",
        spec.theory
    ));
    for law in &spec.laws {
        out.push_str(&format!("- {}\n      {}\n", law.prose(), law.equation()));
    }
    out.push('\n');
    out.push_str(&format!(
        "# {} further consequence equalities (implied by the laws above)\n",
        spec.consequences
    ));
    let coverage = if spec.uncovered_ops.is_empty() {
        "none — every operator participates in a law".to_string()
    } else {
        spec.uncovered_ops.join(", ")
    };
    out.push_str(&format!(
        "# operators in no law (where the spec is silent): {coverage}\n"
    ));
    out
}

impl Spec {
    /// This spec as a `spec_lock::Lock` — its name, committed lock file, and live rendered
    /// text. This is the whole adapter: everything domain-specific about the freeze is in
    /// here (`lock_path` + `render`); the compare (`spec_lock::check`) and the regeneration
    /// write (`spec_lock::bless`, used by `examples/freeze_spec.rs`) are generic. Attached
    /// to the `Spec` value object per the no-rats-nest rule: every public callable hangs
    /// off a typestate.
    pub fn lock(&self) -> Lock {
        Lock {
            name: self.theory.to_string(),
            path: lock_path(self.theory),
            live: render(self),
        }
    }

    /// Check every theory's LIVE spec against its committed lock. On success returns the
    /// theory names verified fresh; on drift returns the names that no longer match (the
    /// fix is to regenerate and ratify the diff).
    ///
    /// Capability: Effectful — reads the committed spec locks from disk (a world-read,
    /// performed by `spec_lock::check`).
    pub fn check_all_fresh() -> Result<Vec<&'static str>, Vec<String>> {
        let specs = all_specs();
        let locks: Vec<Lock> = specs.iter().map(Spec::lock).collect();
        match spec_lock::check(&locks) {
            // spec-lock reports every lock fresh, in order — so the fresh names are exactly
            // the theories', still `&'static` from `Spec` rather than borrowed locally.
            Ok(_) => Ok(specs.iter().map(|s| s.theory).collect()),
            Err(stale) => Err(stale.into_iter().map(String::from).collect()),
        }
    }
}

#[cfg(test)]
mod tests {
    /// The committed spec locks are FRESH: every theory's live discovered spec matches what was
    /// frozen and ratified. A drift (an operator changed behaviour, the engine changed, a domain was
    /// edited) fails here — regenerate with `cargo run --example freeze_spec` and ratify the diff.
    #[test]
    fn the_committed_specs_are_fresh() {
        match super::Spec::check_all_fresh() {
            // all four theories' committed locks match their live discovered spec.
            Ok(fresh) => assert_eq!(
                fresh,
                vec![
                    "interpreter arithmetic",
                    "router",
                    "date calculus",
                    "ttl store"
                ]
            ),
            Err(stale) => panic!(
                "discovered spec drifted from the committed lock for: {}. \
                 Run `cargo run --example freeze_spec` and ratify the diff.",
                stale.join(", ")
            ),
        }
    }
}
