# discovered spec: interpreter arithmetic — generated by `cargo run --example freeze_spec`; ratify changes.

- Addition gives the same result in either order.
      (x + y) = (y + x)
- With Addition, the grouping of three values doesn't matter.
      ((x + y) + z) = (x + (y + z))
- Addition with 0 leaves a value unchanged.
      (0 + x) = x
- Multiplication gives the same result in either order.
      (x * y) = (y * x)
- With Multiplication, the grouping of three values doesn't matter.
      ((x * y) * z) = (x * (y * z))
- Multiplication by 0 always gives 0.
      (0 * x) = 0
- Multiplication with 1 leaves a value unchanged.
      (1 * x) = x
- Multiplication distributes over Addition.
      (x * (y + z)) = ((x * y) + (x * z))
- A value is never less than itself.
      (x < x) = false
- No two distinct programs look the same — the faithful rendering distinguishes every structural and semantic difference.
      U(p) = U(q)  ⟹  p = q   (U = faithful render)

# 316 further consequence equalities (implied by the laws above)
# operators in no law (where the spec is silent): none — every operator participates in a law
