# discovered spec: router — generated by `cargo run --example freeze_spec`; ratify changes.

- With Or, the grouping of three values doesn't matter.
      ((a or b) or c) = (a or (b or c))
- Or of a value with itself gives that value.
      (a or a) = a
- Or with empty leaves a value unchanged.
      (empty or a) = a

# 11 further consequence equalities (implied by the laws above)
# operators in no law (where the spec is silent): none — every operator participates in a law
