# shape catalog: the universal algebraic shapes the discovery engine instantiates — generated by `cargo run --example freeze_shapes`; ratify changes.
#
# This is the engine's LAW-LANGUAGE: every law in every theory's discovered spec is
# an instance of one stanza below. Adding or changing a stanza changes what EVERY
# consumer's discovered spec can say, so it lands as a reviewed diff to this file —
# never as a silent engine edit.

- commutativity
      schema:   (x ⊕ y) = (y ⊕ x)
      gate:     homogeneous binary (s × s → s)
      template: {op} gives the same result in either order.

- associativity
      schema:   ((x ⊕ y) ⊕ z) = (x ⊕ (y ⊕ z))
      gate:     homogeneous binary (s × s → s)
      template: With {op}, the grouping of three values doesn't matter.

- idempotence
      schema:   (x ⊕ x) = x
      gate:     homogeneous binary (s × s → s)
      template: {op} of a value with itself gives that value.

- bias (right-regular)
      schema:   ((x ⊕ y) ⊕ x) = (y ⊕ x)
      gate:     homogeneous binary; skipped when commutative (a commutative operator has no bias to state); excludes the left-regular variant on the grid
      template: With {op}, the later operand wins where the two disagree — re-applying an earlier one cannot overwrite it.

- bias (left-regular)
      schema:   ((x ⊕ y) ⊕ x) = (x ⊕ y)
      gate:     homogeneous binary; skipped when commutative (a commutative operator has no bias to state); excludes the right-regular variant on the grid
      template: With {op}, the earlier operand wins where the two disagree — a later one cannot overwrite it.

- identity
      schema:   (e ⊕ x) = x  (or (x ⊕ e) = x)
      gate:     homogeneous binary plus a constant of its sort; tried on both sides, deduplicated by prose
      template: {op} with {const} leaves a value unchanged.

- annihilation
      schema:   (a ⊕ x) = a  (or (x ⊕ a) = a)
      gate:     homogeneous binary plus a constant of its sort; tried on both sides, deduplicated by prose
      template: {op} by {const} always gives {const}.

- inverse
      schema:   (x ⊕ inv(x)) = e
      gate:     homogeneous binary plus a unary endo and a constant, all on one sort; tried on both sides, deduplicated by prose
      template: {other} inverts {op} — a value {op} its own {other} gives {const}.

- self-inverse
      schema:   (x ⊕ x) = e
      gate:     homogeneous binary plus a constant of its sort — every element its own inverse (the Boolean-group law `inverse` cannot say, because the inverting map is the identity and identity is not an operator)
      template: {op} of a value with itself gives {const} — every element is its own inverse.

- distributivity
      schema:   (x ⊕ (y ⊗ z)) = ((x ⊕ y) ⊗ (x ⊕ z))
      gate:     an ordered pair of distinct homogeneous binaries on one sort
      template: {op} distributes over {other}.

- distributivity (right)
      schema:   ((y ⊗ z) ⊕ x) = ((y ⊕ x) ⊗ (z ⊕ x))
      gate:     an ordered pair of distinct homogeneous binaries on one sort; skipped when the first is commutative (the left-slot law already says it) — the other slot's distributivity, so each argument position carries its own additivity law
      template: {op} distributes over {other} from the right.

- absorption
      schema:   (x ⊕ (x ⊗ y)) = x
      gate:     an ordered pair of distinct homogeneous binaries on one sort
      template: {op} absorbs {other}.

- action identity
      schema:   act(x, e) = x
      gate:     heterogeneous binary s × t → s (an action of t on s) plus a constant of the parameter sort t
      template: {op} with {const} leaves a value unchanged.

- monoid action
      schema:   act(act(x, p), q) = act(x, (p ⊗ q))
      gate:     heterogeneous binary s × t → s plus a homogeneous binary on the parameter sort t
      template: Repeated {op} combines its parameters with {other}.

- action idempotence
      schema:   act(act(x, p), p) = act(x, p)
      gate:     heterogeneous binary s × t → s (an action of t on s)
      template: Repeated {op} with one parameter settles on the first application.

- action commutation
      schema:   act(act(x, p), q) = act(act(x, q), p)
      gate:     heterogeneous binary s × t → s (an action of t on s)
      template: {op} applications commute — the parameter order doesn't matter.

- action equivariance
      schema:   act((x ⊕ y), p) = (act(x, p) ⊕ act(y, p))
      gate:     heterogeneous binary s × t → s (an action of t on s) plus a homogeneous binary on the carrier sort s
      template: {op} distributes over {other} — acting on a combination is combining the actions.

- action fixed point
      schema:   act(c, p) = c
      gate:     heterogeneous binary s × t → s (an action of t on s) plus a constant of the carrier sort s
      template: {op} leaves {const} fixed — no parameter moves it.

- symmetry
      schema:   rel(x, y) = rel(y, x)
      gate:     relation s × s → r (r ≠ s) — a symmetric distance says so here; an order refuses it
      template: {op} is symmetric — the arguments' order doesn't matter.

- irreflexivity
      schema:   rel(x, x) = false
      gate:     relation s × s → r (r ≠ s) whose output sort carries a constant rendering as `false`
      template: A value is never {op} itself.

- self-application
      schema:   rel(x, x) = c
      gate:     relation s × s → r (r ≠ s) plus any other constant of the output sort
      template: {op} of a value with itself gives {const}.

- involution
      schema:   u(u(x)) = x
      gate:     unary s → s
      template: {op} twice returns the original value.

- projection
      schema:   u(u(x)) = u(x)
      gate:     unary s → s
      template: {op} is a projection — applying it twice is applying it once.

- fixed point
      schema:   u(c) = c
      gate:     unary endo s → s plus a constant of its sort
      template: {op} leaves {const} fixed.

- round-trip
      schema:   g(f(x)) = x
      gate:     a pair of distinct unaries f : s → t and g : t → s
      template: {op} undoes {other} — the round trip is the identity.

- homomorphism
      schema:   h((x ⊕ y)) = (h(x) ⊗ h(y))
      gate:     unary h : s → t plus a homogeneous binary on s and one on t
      template: {op} turns {other} into {via}.

- action nontriviality
      schema:   act(x, p) ≠ x  (for some x, p)
      gate:     heterogeneous binary s × t → s (an action of t on s); a witness shape — holds when some parameter moves some value
      template: {op} actually acts — some parameter moves some value.

- non-constancy
      schema:   rel(x, y) ≠ c  (for some x, y)
      gate:     relation s × s → r (r ≠ s) plus a constant of the output sort; a witness shape — holds when the relation escapes the constant somewhere
      template: {op} is not constantly {const}.

- subadditivity
      schema:   le(f((x ⊕ y)), (f(x) ⊕ f(y))) = true  (f(x ⊕ y) ≤ f(x) ⊕ f(y))
      gate:     unary endo s → s, a homogeneous binary on s, and an order relation s × s → r (r ≠ s) whose output sort carries a constant rendering as `true`
      template: {op} is subadditive over {other} (under {via}).

- triangle inequality
      schema:   le(d(x, z), (d(x, y) ⊕ d(y, z))) = true  (d(x, z) ≤ d(x, y) ⊕ d(y, z))
      gate:     a distance d : s × s → t, a homogeneous binary on t, and an order relation t × t → r (r ≠ t) whose output sort carries a constant rendering as `true`; d and the binary must be different operators
      template: {op} satisfies the triangle inequality with {other} (under {via}).

- monotonicity (join form)
      schema:   le(f(x), f((x ⊕ y))) = true  (f(x) ≤ f(x ⊕ y) — monotone in the ⊕-order)
      gate:     unary endo s → s, a homogeneous binary on s (read as the domain's join), and an order relation s × s → r (r ≠ s) whose output sort carries a constant rendering as `true` — the unconditional form of `∀ x ≤ y: f(x) ≤ f(y)` for join-induced orders; the guarded general form stays a roadmap candidate (conditional laws)
      template: {op} is monotone in the {other}-order (under {via}).

- monotonicity (guarded)
      schema:   le(x, y) = true ⟹ le(f(x), f(y)) = true  (∀ x ≤ y: f(x) ≤ f(y))
      gate:     unary endo s → s plus an order relation s × s → r (r ≠ s) whose output sort carries a constant rendering as `true` — the general form of monotonicity, judged only where the premise fires
      template: {op} is monotone under {other}.

- transitivity
      schema:   (le(x, y) ∧ le(y, z)) = true ⟹ le(x, z) = true
      gate:     a relation s × s → r (r ≠ s), a homogeneous binary on r (read as the verdict sort's and), and a constant of r rendering as `true` — judged only where both premise links fire
      template: {op} is transitive (chained through {other}).

- antisymmetry
      schema:   (le(x, y) ∧ le(y, x)) = true ⟹ x = y
      gate:     a relation s × s → r (r ≠ s), a homogeneous binary on r (read as the verdict sort's and), and a constant of r rendering as `true`; the conclusion is CARRIER equality — and a strict order, whose premise is satisfiable nowhere, correctly earns nothing
      template: {op} is antisymmetric — mutual relation forces equality.

- totality
      schema:   (le(x, y) ⊕ le(y, x)) = true  (every pair relates, one way or the other)
      gate:     a relation s × s → r (r ≠ s), a homogeneous binary on r (read as the verdict sort's or), and a constant of r rendering as `true` — a total order says yes somewhere on every pair; a strict order refuses this on the diagonal
      template: {op} is total under {other} — every pair relates one way or the other.

- inert
      schema:   u(x) = x
      gate:     unary endo s → s — an operator the observation cannot see: a normalization already normal, a reorder a stable layout ignores
      template: {op} leaves every value unchanged.

- equivariant map
      schema:   f(act(x, p)) = act2(f(x), p)
      gate:     a unary f : s → t plus an action of u on s and an action of u on t — the commuting square: acting before f is acting after it (rename-then-render = render-then-relabel)
      template: {op} is equivariant — {other} before it becomes {via} after it.
