# the tier partition, DERIVED — the single source the rule dispatch and this lock
# both consume. INTERIOR is non-pub reachability; BOUNDARY is being a DOOR
# (production edge impls, or fronting an interior sibling — the tier-2 relation
# read backwards); ALGEBRA is the reachable remainder; glue takes its
# reachability's tier. KERNEL is a decision, never derived: it is ratified in the
# consumer's own tree (the build.rs allowlist, or a register it parses).
# Regenerate with `BLESS_TIERS=1 cargo build`.
# 70 files: 3 boundary, 5 interior, 52 algebra, 10 kernel.
# rule KERNEL: the trusted floor — exempt from the structural rules; a ratified privilege
# rule BOUNDARY: tier 1 — a domain's strict value-object surface; no loose `pub fn`
# rule INTERIOR: tier 2 — the workshop; mutation and raw collections allowed; no loose `pub fn`
# rule ALGEBRA: the discovered-law / report layer; exempt from the inward rule; no loose `pub fn`

- src/boundary.rs: KERNEL (registered — a decision, never derived)
- src/capability.rs: KERNEL (registered — a decision, never derived)
- src/discover/agenda.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/architect.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/arithmetic.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/attest.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/bite.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/bridge.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/bundle.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/cli.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/coherence.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/cohesion.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/composition.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/date.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/depend.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/derived.rs: ALGEBRA (glue — module declarations and re-exports only; tier by reachability)
- src/discover/desk.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/eduction.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/engine.rs: KERNEL (registered — a decision, never derived)
- src/discover/envelope.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/expect.rs: KERNEL (registered — a decision, never derived)
- src/discover/fabric.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/floor.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/freeze.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/gates.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/genesis.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/infra.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/items.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/judgment.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/layering.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/lift.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/mod.rs: KERNEL (registered — a decision, never derived)
- src/discover/modularize.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/mutation.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/perimeter.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/probes.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/protocol.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/relation.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/residue.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/router.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/scaffold.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/schemata.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/shape.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/squash.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/store.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/substrate.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/system.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/trace.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/verbs.rs: ALGEBRA (glue — module declarations and re-exports only; tier by reachability)
- src/discover/verdict.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/watch.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/world.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/discover/zset.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/gdp.rs: KERNEL (registered — a decision, never derived)
- src/harness.rs: KERNEL (registered — a decision, never derived)
- src/interp/boundary.rs: BOUNDARY (pub-reachable, carries production edges)
- src/interp/internal.rs: INTERIOR (not pub-reachable)
- src/interp/mod.rs: ALGEBRA (glue — module declarations and re-exports only; tier by reachability)
- src/kvstore/internal.rs: INTERIOR (not pub-reachable)
- src/kvstore/mod.rs: ALGEBRA (glue — module declarations and re-exports only; tier by reachability)
- src/kvstore/probes.rs: INTERIOR (not pub-reachable)
- src/kvstore/store.rs: BOUNDARY (pub-reachable, carries production edges)
- src/kvstore/theory.rs: ALGEBRA (pub-reachable, no production edges, fronts nothing)
- src/kvstore/twin.rs: INTERIOR (not pub-reachable)
- src/lib.rs: KERNEL (registered — a decision, never derived)
- src/main.rs: KERNEL (registered — a decision, never derived)
- src/select/boundary.rs: BOUNDARY (pub-reachable, fronts an interior sibling)
- src/select/internal.rs: INTERIOR (not pub-reachable)
- src/select/mod.rs: ALGEBRA (glue — module declarations and re-exports only; tier by reachability)
- src/tests.rs: KERNEL (registered — a decision, never derived)
