//! expectations — the DECLARED-LAWS gate: each module's DISTANCE from its declared
//! algebra (`Distance::of`), red until discovery earns every declared law.
//!
//! GENERATED by genesis from the `relay-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! RED BY DESIGN until the meaning holes are filled: the failure message IS the
//! worklist ("MISSING: ..."). Surprises (discovered, never declared) do not fail —
//! ratify them into the declaration or refute the operator that produced them.

use boundary_spec::discover::expect::Distance;

use relay_app::ops::gauge_ops::Gauge;
use relay_app::ops::mixer_gauge_seam_ops::MixerGaugeSeam;
use relay_app::ops::mixer_ops::Mixer;

/// `mixer` declares 2 law(s); the distance report names any that discovery has
/// not (yet) found true of the meaning.
#[test]
fn mixer_meets_its_declared_expectations() {
    let distance = Distance::of::<Mixer>();
    assert!(distance.is_met(), "{}", distance.render());
}

/// `gauge` declares 1 law(s); the distance report names any that discovery has
/// not (yet) found true of the meaning.
#[test]
fn gauge_meets_its_declared_expectations() {
    let distance = Distance::of::<Gauge>();
    assert!(distance.is_met(), "{}", distance.render());
}

/// The `mixer-gauge seam` spanning theory declares the seam's homomorphism; red names
/// exactly the law the conversion has not yet earned.
#[test]
fn mixer_gauge_seam_meets_its_declared_expectations() {
    let distance = Distance::of::<MixerGaugeSeam>();
    assert!(distance.is_met(), "{}", distance.render());
}
