//! probes — the edge-probe half of the contract: the build shim proves every edge HAS an
//! `impl Probed`; this file is where the probes RUN in CI.
//!
//! GENERATED by genesis for `relay-app` as a STUB: genesis emits no edges, because an edge (a
//! Construction's parse, a Branch's classification, a Guarded edge's witness) is meaning, not
//! structure. Mint the domain's edges on the boundary surface and probe them here — the
//! downstream-fixture's `tests/probes.rs` is the reference shape (entry parse, branch, guarded
//! chain, driven end to end).

// MEANING (filled): this system's edges are the two GENERATED entry constructions (the
// structured range rules derived their predicates) and the conversion crossing the seam —
// probed at the rules' load-bearing points and at the seam's homomorphism edges.

use relay_app::mixer::{Level, Signal};

/// The GENERATED predicates are the declared ranges, verbatim: both edges admitted, both
/// outside neighbours refused, raw values round-tripping unchanged.
#[test]
fn the_generated_constructions_are_the_declared_ranges() {
    for valid in [-8, 0, 8] {
        assert_eq!(Signal::new(valid).expect("in range").get(), valid);
    }
    assert!(Signal::new(-9).is_none() && Signal::new(9).is_none());
    for valid in [0, 16] {
        assert_eq!(Level::new(valid).expect("in range").get(), valid);
    }
    assert!(Level::new(-1).is_none() && Level::new(17).is_none());
}

/// The conversion maps the signal range ONTO the level range edge to edge, monotonically —
/// the shape that makes it the seam's homomorphism.
#[test]
fn cook_rebases_edge_to_edge_and_preserves_order() {
    let signal = |n: i64| Signal::new(n).expect("valid signal");
    assert_eq!(signal(-8).cook().get(), 0, "floor lands on floor");
    assert_eq!(signal(8).cook().get(), 16, "cap lands on cap");
    assert_eq!(
        signal(-3).blend(signal(5)).cook().get(),
        signal(-3).cook().fuse(signal(5).cook()).get(),
        "cook carries blend into fuse — the declared homomorphism, at one concrete point"
    );
}
