//! seams — the DECLARED seam obligations, one test per seam.
//!
//! GENERATED by genesis for `relay-app`. A seam names what a module split must preserve:
//! a `transport` seam shares a sort that is the SAME type on both sides (preserved by
//! construction — genesis defines each value object exactly once); a `transform` seam
//! carries a conversion that must be a HOMOMORPHISM — checked by discovery in the
//! seam's spanning theory when the conversion is NAMED (`via h`), a meaning hole when
//! it is not.

use boundary_spec::discover::system::{SeamKind, SystemReport};

use relay_app::system::RelayApp;

/// TRANSFORM seam `mixer -- gauge` on `Signal` via `cook`: the conversion must be a HOMOMORPHISM,
/// checked by DISCOVERY in the seam's spanning theory (`ops::mixer_gauge_seam_ops`) and verdict-bearing in
/// the compiled graph — this test holds the verdict, and the system lock freezes it.
#[test]
fn seam_mixer_gauge_transform_on_signal() {
    let seam = SystemReport::of::<RelayApp>()
        .seams
        .into_iter()
        .find(|s| (s.left, s.right, s.kind) == ("mixer", "gauge", SeamKind::Transform))
        .expect("declared in src/system.rs");
    assert!(
        seam.status.is_met(),
        "the conversion `cook` does not yet preserve the algebra: {:?}",
        seam.status
    );
}
