# discovered spec: credit meter — generated by `cargo run --example freeze_spec`; ratify changes.

- grant gives the same result in either order.
      (x grant y) = (y grant x)
- With grant, the grouping of three values doesn't matter.
      ((x grant y) grant z) = (x grant (y grant z))
- With renew, the grouping of three values doesn't matter.
      ((x renew y) renew z) = (x renew (y renew z))
- renew of a value with itself gives that value.
      (x renew x) = x
- With renew, the later operand wins where the two disagree — re-applying an earlier one cannot overwrite it.
      ((x renew y) renew x) = (y renew x)

# operators in no law (where the spec is silent): spend
