//! harness — the AUTOGENERATED probing harness: the oracle-free verification that lets a
//! substrate be self-hosted. An edge's laws are DERIVED from its trait, not hand-written per
//! edge; the input distributions are derived from structure (`Sampled`); and the `registry`
//! below ties it all to the interpreter's edges, each registration one (often argument-free)
//! call yielding that edge's whole suite. The harnesses are generic over the traits, so they
//! apply to every present and future edge uniformly. (Named `harness`, not `laws`, because
//! declared laws are only one of its parts — it also holds the generators, the per-shape
//! round-trips, and the registry that runs them.)
//!
//! Division of labour: these derived laws + the structure-derived probes are the ENTIRE
//! positive verification of the interpreter — its evaluation, parsing, and type-checker
//! acceptance carry no hand-written examples. The NEGATIVE tests (a probe CATCHING a planted
//! bug; a rejection) stay hand-written in `tests.rs`. cargo-mutants certifies it all is strong.

use proptest::prelude::*;
use proptest::strategy::BoxedStrategy;
use proptest::test_runner::TestRunner;

use crate::boundary::{
    reconstructs, relation_holds, sensitive_to_all, Capability, Construction, Relation, Unit,
};

// ===== Sampled: a type supplies its OWN canonical input distribution =======

/// A canonical distribution of VALID inputs for a type, built through its own
/// constructor — so a law harness needs no per-edge strategy argument.
pub trait Sampled: Sized + core::fmt::Debug {
    fn sampled() -> BoxedStrategy<Self>;
}

// ===== the generic law harnesses (derived from the traits) ===============

/// LAW (every `Construction`): an admitted raw reconstructs EXACTLY —
/// `reconstruct . parse == id` for every generated raw.
pub fn construction_round_trips<C, S>(c: &C, strategy: S)
where
    C: Construction,
    S: Strategy<Value = C::Raw>,
{
    TestRunner::default()
        .run(&strategy, |raw| {
            prop_assert_eq!(
                reconstructs(c, &raw),
                Some(true),
                "no round-trip at {:?}",
                raw
            );
            Ok(())
        })
        .unwrap();
}

/// LAW (every `Construction`): a `Pure` construction loses nothing, so its residual MUST
/// be `Unit` — a static check between the declared capability and the residual type.
pub fn construction_capability_matches_residual<C: Construction>()
where
    C::Residual: 'static,
{
    let residual_is_unit =
        core::any::TypeId::of::<C::Residual>() == core::any::TypeId::of::<Unit>();
    if C::CAPABILITY == Capability::Pure {
        assert!(
            residual_is_unit,
            "a Pure construction must have a Unit residual (it loses nothing)"
        );
    }
}

/// LAW (any `Relation`): the two routes AGREE on every generated input —
/// `apply(vary x) == rewrite(apply x)` — AND the relation is NON-VACUOUS: it actually fires
/// (its perturbation applies) at least once. The harness OWNS the guard: a probe whose
/// guard never holds — the hand-written-guard antipattern — is REJECTED here, on an ordinary
/// run, with no mutation needed. The author supplies only the relation; everything else
/// (generation, applicability, execution, non-vacuity) is the harness's job.
pub fn relation_laws<R, S>(r: &R, strategy: S)
where
    R: Relation,
    S: Strategy<Value = R::In>,
{
    let applied = core::cell::Cell::new(0u32);
    TestRunner::default()
        .run(&strategy, |x| {
            if let Some(holds) = relation_holds(r, &x) {
                applied.set(applied.get() + 1);
                prop_assert!(holds, "relation fails at {:?}", x);
            }
            Ok(())
        })
        .unwrap();
    assert!(
        applied.get() > 0,
        "relation never applied to any generated input: a vacuous probe, rejected by the harness"
    );
}

/// How many generated inputs a relation actually APPLIED to (its perturbation fired),
/// regardless of whether it held. The non-vacuity count `relation_laws` guards on — exposed
/// so the rejection of a vacuous probe can be demonstrated directly.
pub fn applications<R, S>(r: &R, strategy: S) -> u32
where
    R: Relation,
    S: Strategy<Value = R::In>,
{
    let applied = core::cell::Cell::new(0u32);
    TestRunner::default()
        .run(&strategy, |x| {
            if relation_holds(r, &x).is_some() {
                applied.set(applied.get() + 1);
            }
            Ok(())
        })
        .unwrap();
    applied.get()
}

// ===== per-shape laws: the structure each edge SHAPE entails ================

/// A value object that WRAPS a raw value with a smart constructor and an accessor. The
/// law: `unwrap . wrap == id` — an accessor must report the real contents, not a
/// constant. The cheapest kill for an accessor-to-constant mutant.
pub trait Wrapped: Sized {
    type Raw: Clone + PartialEq + core::fmt::Debug;
    fn wrap(raw: Self::Raw) -> Option<Self>;
    fn unwrap(&self) -> Self::Raw;
}

/// LAW (every `Wrapped`): an admitted raw round-trips through construct-then-read.
pub fn accessor_round_trips<T, S>(strategy: S)
where
    T: Wrapped,
    S: Strategy<Value = T::Raw>,
{
    TestRunner::default()
        .run(&strategy, |raw| {
            if let Some(v) = T::wrap(raw.clone()) {
                prop_assert_eq!(
                    v.unwrap(),
                    raw,
                    "accessor does not report the wrapped value"
                );
            }
            Ok(())
        })
        .unwrap();
}

// ===== the interpreter's input distributions (Sampled / Wrapped) ===========
//
// Each generator is built through the public smart constructors, and a composite's
// generator is DERIVED FROM STRUCTURE (a `Value` from `Int`/`bool`, an `Expr`
// recursively from its variants) — the structure supplies the distribution.

impl Sampled for crate::interp::boundary::Int {
    fn sampled() -> BoxedStrategy<Self> {
        (0i64..=100_000)
            .prop_map(|n| crate::interp::boundary::Int::new(n).unwrap())
            .boxed()
    }
}
impl Sampled for crate::interp::boundary::Ident {
    fn sampled() -> BoxedStrategy<Self> {
        prop_oneof![Just("x"), Just("y"), Just("z")]
            .prop_map(|s| crate::interp::boundary::Ident::new(s).unwrap())
            .boxed()
    }
}
impl Sampled for crate::interp::boundary::Value {
    fn sampled() -> BoxedStrategy<Self> {
        use crate::interp::boundary::{Int, Value};
        prop_oneof![
            <Int as Sampled>::sampled().prop_map(Value::Int),
            any::<bool>().prop_map(Value::Bool),
        ]
        .boxed()
    }
}
impl Sampled for crate::interp::boundary::Expr {
    fn sampled() -> BoxedStrategy<Self> {
        use crate::interp::boundary::{Expr, Ident, Op};
        let leaf = prop_oneof![
            (0i64..=999).prop_map(|n| Expr::int(n).unwrap()),
            any::<bool>().prop_map(Expr::boolean),
            <Ident as Sampled>::sampled().prop_map(Expr::var),
        ];
        leaf.prop_recursive(4, 48, 3, |inner| {
            let op = prop_oneof![Just(Op::Add), Just(Op::Mul), Just(Op::Lt)];
            prop_oneof![
                (op, inner.clone(), inner.clone()).prop_map(|(o, a, b)| Expr::bin(o, a, b)),
                (inner.clone(), inner.clone(), inner.clone())
                    .prop_map(|(c, t, e)| Expr::cond(c, t, e)),
                (<Ident as Sampled>::sampled(), inner.clone(), inner.clone())
                    .prop_map(|(n, v, b)| Expr::bind(n, v, b)),
            ]
        })
        .boxed()
    }
}

impl Wrapped for crate::interp::boundary::Int {
    type Raw = i64;
    fn wrap(raw: i64) -> Option<Self> {
        crate::interp::boundary::Int::new(raw)
    }
    fn unwrap(&self) -> i64 {
        self.get()
    }
}
impl Wrapped for crate::interp::boundary::Ident {
    type Raw = String;
    fn wrap(raw: String) -> Option<Self> {
        crate::interp::boundary::Ident::new(&raw)
    }
    fn unwrap(&self) -> String {
        self.get().to_string()
    }
}

// ===== the registry: register an edge; the laws are automatic =============

mod registry {
    use super::*;
    use crate::gdp::with_seed;
    use crate::interp::boundary::{Check, Eval, Expr, Ident, Int, Op, Parse, Value};

    // canonical source for the `Parse` round-trip: `Expr` is self-sampling, so the
    // generator is just `Expr::sampled().render()`.
    fn canonical_source() -> impl Strategy<Value = String> {
        <Expr as Sampled>::sampled().prop_map(|e| e.render())
    }

    // closed, INT-typed expressions, so `Check` always admits and `eval` is total.
    fn int_expr() -> impl Strategy<Value = Expr> {
        let leaf = (0i64..=99).prop_map(|n| Expr::int(n).unwrap());
        leaf.prop_recursive(3, 16, 2, |inner| {
            prop_oneof![
                (inner.clone(), inner.clone()).prop_map(|(a, b)| Expr::bin(Op::Add, a, b)),
                (inner.clone(), inner.clone()).prop_map(|(a, b)| Expr::bin(Op::Mul, a, b)),
            ]
        })
    }

    // evaluate a closed, well-typed expression through the BOUNDARY (Check then the
    // WellTyped-guarded Eval) — the `apply` the relations probe.
    fn eval_closed(e: &Expr) -> Value {
        with_seed(|seed| {
            let named = seed.new_named(e.clone());
            let proof = Check
                .classify(&named)
                .expect("a closed int expr is well-typed");
            *Eval.run(&named, &proof).value()
        })
    }

    // ===== algebraic LAWS: declare the invariant, the probe of it is GENERATED =====
    //
    // The author states only the MEANING — an algebraic law the operator satisfies. Each
    // `Law` fans out into a full probe: a first-class `Relation` run over a derived
    // generator, with the applicability guard and the non-vacuity check owned by the
    // harness. No `apply`/`vary`/`rewrite` is hand-written per law; declaring the law IS
    // writing the probe.

    #[derive(Clone, Debug)]
    enum Law {
        /// `x op e == x` — `e` is a right identity for `op`.
        Identity { op: Op, element: Expr },
        /// `x op y == y op x`.
        Commutative { op: Op },
        /// `x op x == value` — equal operands collapse to a constant (e.g. `<` is
        /// irreflexive, collapsing to `false`).
        Reflexive { op: Op, value: Value },
    }

    /// The probe GENERATED from a law — a `Relation` over the evaluator. The author never
    /// writes this; `Law` produces it.
    struct LawProbe {
        law: Law,
    }
    impl Relation for LawProbe {
        type In = Expr;
        type Out = Value;
        fn apply(&self, x: &Expr) -> Value {
            match &self.law {
                Law::Reflexive { op, .. } => eval_closed(&Expr::bin(*op, x.clone(), x.clone())),
                _ => eval_closed(x),
            }
        }
        fn vary(&self, x: &Expr) -> Option<Expr> {
            match &self.law {
                Law::Identity { op, element } => Some(Expr::bin(*op, x.clone(), element.clone())),
                Law::Commutative { op } => match x {
                    Expr::Bin(o, a, b) if o == op => {
                        Some(Expr::bin(*op, (**b).clone(), (**a).clone()))
                    }
                    _ => None,
                },
                Law::Reflexive { .. } => Some(x.clone()),
            }
        }
        fn rewrite(&self, y: Value) -> Value {
            match &self.law {
                Law::Reflexive { value, .. } => *value,
                _ => y,
            }
        }
    }

    /// Operand expressions built around a top-level `op` node, so a commutativity probe's
    /// perturbation always fires (non-vacuity).
    fn binary(op: Op) -> impl Strategy<Value = Expr> {
        (int_expr(), int_expr()).prop_map(move |(a, b)| Expr::bin(op, a, b))
    }

    /// Generate and run the FULL probe of a declared law — the author wrote only the `Law`.
    fn prove_law(law: &Law) {
        let probe = LawProbe { law: law.clone() };
        match law {
            Law::Commutative { op } => relation_laws(&probe, binary(*op)),
            _ => relation_laws(&probe, int_expr()),
        }
    }

    /// The interpreter's declared algebra — the ONLY hand-written part (the meaning itself).
    /// Each entry generates its whole probe.
    fn interpreter_laws() -> Vec<Law> {
        vec![
            Law::Identity {
                op: Op::Add,
                element: Expr::int(0).unwrap(),
            },
            Law::Identity {
                op: Op::Mul,
                element: Expr::int(1).unwrap(),
            },
            Law::Commutative { op: Op::Add },
            Law::Commutative { op: Op::Mul },
            Law::Reflexive {
                op: Op::Lt,
                value: Value::Bool(false),
            },
        ]
    }

    // a deliberately FALSE relation and an inapplicable one, to pin `relation_holds`.
    crate::relation!(
        /// FALSE by construction: `x + 1` does not evaluate as `x`.
        Increment: Expr => Value,
        apply = eval_closed,
        vary = |x: &Expr| Some(Expr::bin(Op::Add, x.clone(), Expr::int(1).unwrap())),
        rewrite = |y| y);
    crate::relation!(
        /// Never applicable: `vary` always declines.
        NeverApplies: Expr => Value,
        apply = eval_closed,
        vary = |_x: &Expr| None,
        rewrite = |y| y);

    /// The interpreter's entry edge: `render . parse == id` over generated canonical
    /// source. This single registration certifies the whole lex/parse/unparse path.
    #[test]
    fn parse_is_probed() {
        construction_round_trips(&Parse, canonical_source());
        construction_capability_matches_residual::<Parse>();
    }

    /// The FUSED universal probe over RANDOM structures: a faithful map (`render`) is
    /// sensitive to every derived degree of freedom at every generated `Expr` — random input
    /// generation (proptest) crossed with the structure-derived per-dimension perturbations.
    #[test]
    fn render_is_universally_sensitive() {
        TestRunner::default()
            .run(&<Expr as Sampled>::sampled(), |e| {
                prop_assert!(
                    sensitive_to_all(|x: &Expr| x.render(), &e),
                    "render missed a dimension at {:?}",
                    e
                );
                Ok(())
            })
            .unwrap();
    }

    /// `parse . render == id` on the AST, oracle = `Expr` equality, generator
    /// independent of `render` — so a `render`-to-constant mutant is caught.
    #[test]
    fn parse_inverts_render() {
        TestRunner::default()
            .run(&<Expr as Sampled>::sampled(), |e| {
                prop_assert_eq!(Parse.parse_str(&e.render()), Some(e.clone()));
                Ok(())
            })
            .unwrap();
    }

    /// The value frontier, certified by DECLARED LAWS: each `Law` in the interpreter's
    /// algebra generates and runs its own full probe — value testing with no oracle and no
    /// per-law plumbing.
    #[test]
    fn eval_laws_are_probed() {
        for law in interpreter_laws() {
            prove_law(&law);
        }
    }

    /// The evaluator's every arm, pinned ORACLE-FREE — each result compared to an
    /// INDEPENDENT computation (raw integer arithmetic / comparison, or the eval of the
    /// branch the construct names), so `Add`/`Mul`/`Lt`, the conditional, and `let`/`var`
    /// (incl. shadowing) are all certified WITHOUT a hand-written example. This is what lets
    /// the interpreter's evaluation be self-hosted: the apparatus suffices, the examples go.
    #[test]
    fn eval_semantics_are_probed() {
        fn as_int(v: &Value) -> i64 {
            match v {
                Value::Int(i) => i.get(),
                Value::Bool(_) => unreachable!("a closed int expr evaluates to an int"),
            }
        }
        let x = Ident::new("x").expect("valid identifier");
        // BOUNDED operands: small enough that the products below cannot overflow `i64`
        // (the evaluator and the independent check both compute `av * bv`). Still compound
        // (Add/Mul nesting), so the evaluator's recursion is exercised, not just leaves.
        let bounded = {
            let leaf = (0i64..=20).prop_map(|n| Expr::int(n).unwrap());
            leaf.prop_recursive(2, 8, 2, |inner| {
                prop_oneof![
                    (inner.clone(), inner.clone()).prop_map(|(a, b)| Expr::bin(Op::Add, a, b)),
                    (inner.clone(), inner.clone()).prop_map(|(a, b)| Expr::bin(Op::Mul, a, b)),
                ]
            })
        };
        TestRunner::default()
            .run(&(bounded.clone(), bounded.clone(), bounded), |(a, b, c)| {
                let (av, bv, cv) = (
                    as_int(&eval_closed(&a)),
                    as_int(&eval_closed(&b)),
                    as_int(&eval_closed(&c)),
                );
                // arithmetic and comparison against the raw integer operations:
                prop_assert_eq!(
                    eval_closed(&Expr::bin(Op::Add, a.clone(), b.clone())),
                    Value::Int(Int::new(av + bv).unwrap())
                );
                prop_assert_eq!(
                    eval_closed(&Expr::bin(Op::Mul, a.clone(), b.clone())),
                    Value::Int(Int::new(av * bv).unwrap())
                );
                prop_assert_eq!(
                    eval_closed(&Expr::bin(Op::Lt, a.clone(), b.clone())),
                    Value::Bool(av < bv)
                );
                // the conditional selects the branch its (literal) condition names:
                prop_assert_eq!(
                    eval_closed(&Expr::cond(Expr::boolean(true), a.clone(), b.clone())),
                    eval_closed(&a)
                );
                prop_assert_eq!(
                    eval_closed(&Expr::cond(Expr::boolean(false), a.clone(), b.clone())),
                    eval_closed(&b)
                );
                // `let` binds and `var` resolves: `let x = a in (x + c) == a + c`:
                prop_assert_eq!(
                    eval_closed(&Expr::bind(
                        x.clone(),
                        a.clone(),
                        Expr::bin(Op::Add, Expr::var(x.clone()), c.clone())
                    )),
                    Value::Int(Int::new(av + cv).unwrap())
                );
                // shadowing: the inner binding wins:
                prop_assert_eq!(
                    eval_closed(&Expr::bind(
                        x.clone(),
                        a.clone(),
                        Expr::bind(x.clone(), b.clone(), Expr::var(x.clone()))
                    )),
                    eval_closed(&b)
                );
                Ok(())
            })
            .unwrap();
    }

    /// NEGATIVE: `relation_holds` distinguishes holds / violated / inapplicable, so a
    /// vacuous-pass mutant cannot survive. The positive case is a generated law probe.
    #[test]
    fn relation_holds_distinguishes_outcomes() {
        let five = Expr::int(5).unwrap();
        let identity = LawProbe {
            law: Law::Identity {
                op: Op::Add,
                element: Expr::int(0).unwrap(),
            },
        };
        assert_eq!(relation_holds(&identity, &five), Some(true));
        assert_eq!(relation_holds(&Increment, &five), Some(false));
        assert_eq!(relation_holds(&NeverApplies, &five), None);
    }

    /// The HARNESS owns the guard: a probe that never applies is rejected by the
    /// non-vacuity check, on an ordinary run — the structural cure for the hand-written
    /// guard antipattern (no mutation needed to catch it). A real law applies; `NeverApplies`
    /// does not, so `relation_laws` would reject it.
    #[test]
    fn the_harness_rejects_a_vacuous_probe() {
        let identity = LawProbe {
            law: Law::Identity {
                op: Op::Add,
                element: Expr::int(0).unwrap(),
            },
        };
        assert!(
            applications(&identity, int_expr()) > 0,
            "a real law applies"
        );
        assert_eq!(
            applications(&NeverApplies, int_expr()),
            0,
            "a vacuous probe never applies — the harness's non-vacuity guard catches it"
        );
    }

    /// Accessors report the real contents (`unwrap . wrap == id`).
    #[test]
    fn accessors_round_trip() {
        accessor_round_trips::<Int, _>(0i64..=100_000);
        accessor_round_trips::<Ident, _>(prop_oneof![
            Just("x".to_string()),
            Just("foo".to_string()),
            Just("bar".to_string())
        ]);
    }

    /// BRANCH/GUARDED coherence: a value the `Branch` (`Check`) admits, the `Guarded`
    /// edge (`Eval`) can total-ly process — the witness makes evaluation total.
    #[test]
    fn branch_guard_coheres() {
        TestRunner::default()
            .run(&int_expr(), |e| {
                let evaluable = with_seed(|seed| {
                    let named = seed.new_named(e.clone());
                    match Check.classify(&named) {
                        Ok(proof) => {
                            Eval.run(&named, &proof);
                            true
                        }
                        Err(_) => false,
                    }
                });
                prop_assert!(
                    evaluable,
                    "an int expr must type-check and evaluate: {:?}",
                    e
                );
                Ok(())
            })
            .unwrap();
    }
}
