//! laws — AUTOGENERATED probing: an edge's laws are DERIVED from its trait, not
//! hand-written per edge. With the interpreter as the sole substrate, the `registry`
//! below registers interp's edges; each registration is one (often argument-free) call
//! and yields that edge's whole structural suite. The harnesses are generic over the
//! traits, so they apply to every present and future edge uniformly.
//!
//! Division of labour: these are the STRUCTURAL/relational laws that follow from the
//! algebra; the NEGATIVE tests (a probe CATCHING a planted bug) stay hand-written.
//! cargo-mutants then certifies these derived laws are strong.

use proptest::prelude::*;
use proptest::strategy::BoxedStrategy;
use proptest::test_runner::TestRunner;

use crate::boundary::{reconstructs, relation_holds, Capability, Construction, Relation, Unit};

// ===== Sampled: a type supplies its OWN canonical input distribution =======

/// A canonical distribution of VALID inputs for a type, built through its own
/// constructor — so a law harness needs no per-edge strategy argument.
pub trait Sampled: Sized + core::fmt::Debug {
    fn sampled() -> BoxedStrategy<Self>;
}

// ===== the generic law harnesses (derived from the traits) ===============

/// LAW (every `Construction`): an admitted raw reconstructs EXACTLY —
/// `reconstruct . parse == id` for every generated raw.
pub fn construction_round_trips<C, S>(c: &C, strategy: S)
where
    C: Construction,
    S: Strategy<Value = C::Raw>,
{
    TestRunner::default()
        .run(&strategy, |raw| {
            prop_assert_eq!(
                reconstructs(c, &raw),
                Some(true),
                "no round-trip at {:?}",
                raw
            );
            Ok(())
        })
        .unwrap();
}

/// LAW (every `Construction`): a `Pure` construction loses nothing, so its residual MUST
/// be `Unit` — a static check between the declared capability and the residual type.
pub fn construction_capability_matches_residual<C: Construction>()
where
    C::Residual: 'static,
{
    let residual_is_unit =
        core::any::TypeId::of::<C::Residual>() == core::any::TypeId::of::<Unit>();
    if C::CAPABILITY == Capability::Pure {
        assert!(
            residual_is_unit,
            "a Pure construction must have a Unit residual (it loses nothing)"
        );
    }
}

/// LAW (any `Relation`): the two routes AGREE on every generated input —
/// `apply(vary x) == rewrite(apply x)`. Oracle-free value testing for ANY edge shape,
/// including the `Guarded` eval whose `apply` drives a whole Parse/Check/Eval pipeline.
pub fn relation_laws<R, S>(r: &R, strategy: S)
where
    R: Relation,
    S: Strategy<Value = R::In>,
{
    TestRunner::default()
        .run(&strategy, |x| {
            if let Some(holds) = relation_holds(r, &x) {
                prop_assert!(holds, "relation fails at {:?}", x);
            }
            Ok(())
        })
        .unwrap();
}

// ===== per-shape laws: the structure each edge SHAPE entails ================

/// A value object that WRAPS a raw value with a smart constructor and an accessor. The
/// law: `unwrap . wrap == id` — an accessor must report the real contents, not a
/// constant. The cheapest kill for an accessor-to-constant mutant.
pub trait Wrapped: Sized {
    type Raw: Clone + PartialEq + core::fmt::Debug;
    fn wrap(raw: Self::Raw) -> Option<Self>;
    fn unwrap(&self) -> Self::Raw;
}

/// LAW (every `Wrapped`): an admitted raw round-trips through construct-then-read.
pub fn accessor_round_trips<T, S>(strategy: S)
where
    T: Wrapped,
    S: Strategy<Value = T::Raw>,
{
    TestRunner::default()
        .run(&strategy, |raw| {
            if let Some(v) = T::wrap(raw.clone()) {
                prop_assert_eq!(
                    v.unwrap(),
                    raw,
                    "accessor does not report the wrapped value"
                );
            }
            Ok(())
        })
        .unwrap();
}

// ===== the interpreter's input distributions (Sampled / Wrapped) ===========
//
// Each generator is built through the public smart constructors, and a composite's
// generator is DERIVED FROM STRUCTURE (a `Value` from `Int`/`bool`, an `Expr`
// recursively from its variants) — the structure supplies the distribution.

impl Sampled for crate::interp::boundary::Int {
    fn sampled() -> BoxedStrategy<Self> {
        (0i64..=100_000)
            .prop_map(|n| crate::interp::boundary::Int::new(n).unwrap())
            .boxed()
    }
}
impl Sampled for crate::interp::boundary::Ident {
    fn sampled() -> BoxedStrategy<Self> {
        prop_oneof![Just("x"), Just("y"), Just("z")]
            .prop_map(|s| crate::interp::boundary::Ident::new(s).unwrap())
            .boxed()
    }
}
impl Sampled for crate::interp::boundary::Value {
    fn sampled() -> BoxedStrategy<Self> {
        use crate::interp::boundary::{Int, Value};
        prop_oneof![
            <Int as Sampled>::sampled().prop_map(Value::Int),
            any::<bool>().prop_map(Value::Bool),
        ]
        .boxed()
    }
}
impl Sampled for crate::interp::boundary::Expr {
    fn sampled() -> BoxedStrategy<Self> {
        use crate::interp::boundary::{Expr, Ident, Op};
        let leaf = prop_oneof![
            (0i64..=999).prop_map(|n| Expr::int(n).unwrap()),
            any::<bool>().prop_map(Expr::boolean),
            <Ident as Sampled>::sampled().prop_map(Expr::var),
        ];
        leaf.prop_recursive(4, 48, 3, |inner| {
            let op = prop_oneof![Just(Op::Add), Just(Op::Mul), Just(Op::Lt)];
            prop_oneof![
                (op, inner.clone(), inner.clone()).prop_map(|(o, a, b)| Expr::bin(o, a, b)),
                (inner.clone(), inner.clone(), inner.clone())
                    .prop_map(|(c, t, e)| Expr::cond(c, t, e)),
                (<Ident as Sampled>::sampled(), inner.clone(), inner.clone())
                    .prop_map(|(n, v, b)| Expr::bind(n, v, b)),
            ]
        })
        .boxed()
    }
}

impl Wrapped for crate::interp::boundary::Int {
    type Raw = i64;
    fn wrap(raw: i64) -> Option<Self> {
        crate::interp::boundary::Int::new(raw)
    }
    fn unwrap(&self) -> i64 {
        self.get()
    }
}
impl Wrapped for crate::interp::boundary::Ident {
    type Raw = String;
    fn wrap(raw: String) -> Option<Self> {
        crate::interp::boundary::Ident::new(&raw)
    }
    fn unwrap(&self) -> String {
        self.get().to_string()
    }
}

// ===== the registry: register an edge; the laws are automatic =============

mod registry {
    use super::*;
    use crate::gdp::with_seed;
    use crate::interp::boundary::{Check, Eval, Expr, Ident, Int, Op, Parse, Value};

    // canonical source for the `Parse` round-trip: `Expr` is self-sampling, so the
    // generator is just `Expr::sampled().render()`.
    fn canonical_source() -> impl Strategy<Value = String> {
        <Expr as Sampled>::sampled().prop_map(|e| e.render())
    }

    // closed, INT-typed expressions, so `Check` always admits and `eval` is total.
    fn int_expr() -> impl Strategy<Value = Expr> {
        let leaf = (0i64..=99).prop_map(|n| Expr::int(n).unwrap());
        leaf.prop_recursive(3, 16, 2, |inner| {
            prop_oneof![
                (inner.clone(), inner.clone()).prop_map(|(a, b)| Expr::bin(Op::Add, a, b)),
                (inner.clone(), inner.clone()).prop_map(|(a, b)| Expr::bin(Op::Mul, a, b)),
            ]
        })
    }

    // evaluate a closed, well-typed expression through the BOUNDARY (Check then the
    // WellTyped-guarded Eval) — the `apply` the relations probe.
    fn eval_closed(e: &Expr) -> Value {
        with_seed(|seed| {
            let named = seed.new_named(e.clone());
            let proof = Check
                .classify(&named)
                .expect("a closed int expr is well-typed");
            *Eval.run(&named, &proof).value()
        })
    }

    // oracle-free RELATIONS over the interpreter's value frontier, each one grammar line
    // via `relation!` — only `apply`/`vary`/`rewrite` carry information.
    crate::relation!(
        /// Additive identity: `x + 0` evaluates as `x`.
        AddIdentity: Expr => Value,
        apply = eval_closed,
        vary = |x: &Expr| Some(Expr::bin(Op::Add, x.clone(), Expr::int(0).unwrap())),
        rewrite = |y| y);
    crate::relation!(
        /// Multiplicative identity: `x * 1` evaluates as `x`.
        MulIdentity: Expr => Value,
        apply = eval_closed,
        vary = |x: &Expr| Some(Expr::bin(Op::Mul, x.clone(), Expr::int(1).unwrap())),
        rewrite = |y| y);
    crate::relation!(
        /// Strict `<` is irreflexive: `x < x` is always `false`.
        LtIrreflexive: Expr => Value,
        apply = |x: &Expr| eval_closed(&Expr::bin(Op::Lt, x.clone(), x.clone())),
        vary = |x: &Expr| Some(x.clone()),
        rewrite = |_y| Value::Bool(false));
    // a deliberately FALSE relation and an inapplicable one, to pin `relation_holds`.
    crate::relation!(
        /// FALSE by construction: `x + 1` does not evaluate as `x`.
        Increment: Expr => Value,
        apply = eval_closed,
        vary = |x: &Expr| Some(Expr::bin(Op::Add, x.clone(), Expr::int(1).unwrap())),
        rewrite = |y| y);
    crate::relation!(
        /// Never applicable: `vary` always declines.
        NeverApplies: Expr => Value,
        apply = eval_closed,
        vary = |_x: &Expr| None,
        rewrite = |y| y);

    /// The interpreter's entry edge: `render . parse == id` over generated canonical
    /// source. This single registration certifies the whole lex/parse/unparse path.
    #[test]
    fn parse_is_probed() {
        construction_round_trips(&Parse, canonical_source());
        construction_capability_matches_residual::<Parse>();
    }

    /// `parse . render == id` on the AST, oracle = `Expr` equality, generator
    /// independent of `render` — so a `render`-to-constant mutant is caught.
    #[test]
    fn parse_inverts_render() {
        TestRunner::default()
            .run(&<Expr as Sampled>::sampled(), |e| {
                prop_assert_eq!(Parse.parse_str(&e.render()), Some(e.clone()));
                Ok(())
            })
            .unwrap();
    }

    /// The value frontier as oracle-free relations (additive/multiplicative identity,
    /// strict-`<`) — value testing with no oracle and no per-input code.
    #[test]
    fn eval_relations_are_probed() {
        relation_laws(&AddIdentity, int_expr());
        relation_laws(&MulIdentity, int_expr());
        relation_laws(&LtIrreflexive, int_expr());
    }

    /// NEGATIVE: `relation_holds` distinguishes holds / violated / inapplicable, so a
    /// vacuous-pass mutant cannot survive.
    #[test]
    fn relation_holds_distinguishes_outcomes() {
        let five = Expr::int(5).unwrap();
        assert_eq!(relation_holds(&AddIdentity, &five), Some(true));
        assert_eq!(relation_holds(&Increment, &five), Some(false));
        assert_eq!(relation_holds(&NeverApplies, &five), None);
    }

    /// Accessors report the real contents (`unwrap . wrap == id`).
    #[test]
    fn accessors_round_trip() {
        accessor_round_trips::<Int, _>(0i64..=100_000);
        accessor_round_trips::<Ident, _>(prop_oneof![
            Just("x".to_string()),
            Just("foo".to_string()),
            Just("bar".to_string())
        ]);
    }

    /// BRANCH/GUARDED coherence: a value the `Branch` (`Check`) admits, the `Guarded`
    /// edge (`Eval`) can total-ly process — the witness makes evaluation total.
    #[test]
    fn branch_guard_coheres() {
        TestRunner::default()
            .run(&int_expr(), |e| {
                let evaluable = with_seed(|seed| {
                    let named = seed.new_named(e.clone());
                    match Check.classify(&named) {
                        Ok(proof) => {
                            Eval.run(&named, &proof);
                            true
                        }
                        Err(_) => false,
                    }
                });
                prop_assert!(
                    evaluable,
                    "an int expr must type-check and evaluate: {:?}",
                    e
                );
                Ok(())
            })
            .unwrap();
    }
}
