//! laws — AUTOGENERATED probing: an edge's laws are DERIVED from its trait, not
//! hand-written per edge. This is how the category pays for itself — repeatable
//! testing without writing tests.
//!
//! Being a `Morphism` ENTAILS the residual round-trip (`backward . forward == id`)
//! and the capability law (`Pure => Unit residual`); being a `Construction` entails
//! the parse round-trip (`reconstruct . parse == id`); registering a `Perturbation`
//! entails the completeness probe. So a NEW edge gets its whole structural suite by
//! REGISTERING it with an input strategy — one line in `registry` below — instead of
//! re-writing the same assertions. The harnesses are generic over the trait, so they
//! apply to every present and future edge uniformly.
//!
//! Division of labour with the rest of the suite: these are the STRUCTURAL laws that
//! follow from the algebra; the DOMAIN laws that don't (commutativity, involution,
//! the quantitative coefficient) stay hand-written in `properties.rs`. cargo-mutants
//! then certifies these derived laws are strong and surfaces any degree of freedom a
//! generated suite still misses (the generation+selection loop, `select`/`synth`).

use core::any::TypeId;

use proptest::prelude::*;
use proptest::test_runner::TestRunner;

use crate::boundary::{
    construction_probe, probe, reconstructs, run, Capability, Construction, Morphism, Perturbation,
    RawPerturbation, Unit,
};

// ===== the generic law harnesses (derived from the traits) ===============

/// LAW (every `Morphism`): with its residual retained, `backward . forward == id`
/// for every generated input. Derived purely from `Morphism` — no per-edge assertion.
pub fn morphism_round_trips<M, S>(m: &M, strategy: S)
where
    M: Morphism,
    S: Strategy<Value = M::In>,
{
    TestRunner::default()
        .run(&strategy, |x| {
            let carried = run(m, &x);
            let recovered = carried.invert(m);
            prop_assert_eq!(recovered.as_ref(), Some(&x));
            Ok(())
        })
        .unwrap();
}

/// LAW (a `Morphism` + a `Perturbation` of a lossy dimension): the residual is
/// COMPLETE on every generated input — output invariant, residual responds, the
/// perturbed input round-trips.
pub fn morphism_residual_complete<M, P, S>(m: &M, p: &P, strategy: S)
where
    M: Morphism,
    P: Perturbation<M>,
    S: Strategy<Value = M::In>,
{
    TestRunner::default()
        .run(&strategy, |x| {
            let pr = probe(m, p, &x).expect("the perturbation applies on this strategy");
            prop_assert!(pr.residual_complete(), "incomplete residual at {:?}", x);
            Ok(())
        })
        .unwrap();
}

/// LAW (every `Construction`): an admitted raw reconstructs EXACTLY —
/// `reconstruct . parse == id` for every generated raw.
pub fn construction_round_trips<C, S>(c: &C, strategy: S)
where
    C: Construction,
    S: Strategy<Value = C::Raw>,
{
    TestRunner::default()
        .run(&strategy, |raw| {
            prop_assert_eq!(
                reconstructs(c, &raw),
                Some(true),
                "no round-trip at {:?}",
                raw
            );
            Ok(())
        })
        .unwrap();
}

/// LAW (a `Construction` + a `RawPerturbation`): the residual is COMPLETE on every
/// generated raw — the entry-edge analog of `morphism_residual_complete`.
pub fn construction_residual_complete<C, P, S>(c: &C, p: &P, strategy: S)
where
    C: Construction,
    P: RawPerturbation<C>,
    S: Strategy<Value = C::Raw>,
{
    TestRunner::default()
        .run(&strategy, |raw| {
            let pr = construction_probe(c, p, &raw).expect("the perturbation applies");
            prop_assert!(pr.residual_complete(), "incomplete residual at {:?}", raw);
            Ok(())
        })
        .unwrap();
}

/// LAW (every `Morphism`): a `Pure` edge loses nothing, so its residual MUST be
/// `Unit`. A static, input-free consistency check between the declared capability and
/// the residual type — it catches a `Pure` declared on a lossy map (or vice versa).
pub fn capability_matches_residual<M: Morphism>()
where
    M::Residual: 'static,
{
    let residual_is_unit = TypeId::of::<M::Residual>() == TypeId::of::<Unit>();
    if M::CAPABILITY == Capability::Pure {
        assert!(
            residual_is_unit,
            "a Pure morphism must have a Unit residual (it loses nothing)"
        );
    }
}

/// The construction analog of `capability_matches_residual`.
pub fn construction_capability_matches_residual<C: Construction>()
where
    C::Residual: 'static,
{
    let residual_is_unit = TypeId::of::<C::Residual>() == TypeId::of::<Unit>();
    if C::CAPABILITY == Capability::Pure {
        assert!(
            residual_is_unit,
            "a Pure construction must have a Unit residual (it loses nothing)"
        );
    }
}

// ===== the registry: one line per edge, the laws come for free ===========

#[cfg(test)]
mod registry {
    use super::*;
    use crate::ledger::boundary::{
        Account, AccountSummary, Aggregate, Cents, PadName, ParseAccount, ParseCents,
        ParseTransaction, Posting, ReorderPostings, Round, Split, Transaction,
    };
    use crate::linear::boundary::{Quantity, Scale};

    // ----- strategies: the ONLY per-edge input. The laws themselves are derived. ---

    fn cents_raw() -> impl Strategy<Value = i64> {
        -100_000_000i64..=100_000_000
    }

    fn account_raw() -> impl Strategy<Value = String> {
        (
            prop_oneof![Just(""), Just(" "), Just("  "), Just("\t")],
            prop_oneof!["Cash", "Revenue", "Tax", "Fees"],
            prop_oneof![Just(""), Just(" "), Just("  ")],
        )
            .prop_map(|(lead, name, trail)| format!("{lead}{name}{trail}"))
    }

    fn posting(amount: impl Strategy<Value = i64>) -> impl Strategy<Value = Posting> {
        (
            prop_oneof![Just("Cash"), Just("Revenue"), Just("Tax"), Just("Fees")],
            amount,
        )
            .prop_map(|(a, m)| Posting::new(Account::new(a).unwrap(), Cents::new(m).unwrap()))
    }

    fn postings(min: usize) -> impl Strategy<Value = Vec<Posting>> {
        prop::collection::vec(posting(-1_000_000i64..=1_000_000), min..=8)
    }

    fn transaction() -> impl Strategy<Value = Transaction> {
        postings(1).prop_map(|p| Transaction::new(p).unwrap())
    }

    /// Substantial amounts so the `Split` perturbation actually moves multiplicity.
    fn tx_substantial() -> impl Strategy<Value = Transaction> {
        prop::collection::vec(
            posting(prop_oneof![1_000i64..=1_000_000, -1_000_000i64..=-1_000]),
            2..=8,
        )
        .prop_map(|p| Transaction::new(p).unwrap())
    }

    fn summary() -> impl Strategy<Value = AccountSummary> {
        transaction().prop_map(|t| Aggregate.forward(&t).0)
    }

    fn quantity() -> impl Strategy<Value = Quantity> {
        (-50_000i64..=50_000).prop_map(|n| Quantity::new(n).unwrap())
    }

    // ----- each edge: register it; the laws are automatic (no assertions here) -----

    #[test]
    fn aggregate_is_probed() {
        morphism_round_trips(&Aggregate, transaction());
        morphism_residual_complete(&Aggregate, &Split, tx_substantial());
        capability_matches_residual::<Aggregate>();
    }

    #[test]
    fn round_is_probed() {
        morphism_round_trips(&Round, summary());
        // NB: completeness needs a perturbation matched to the lost dimension. A bare
        // +1c `NudgeCents` can cross a dollar boundary (changing the rounded output),
        // so it is NOT complete over arbitrary summaries — the matched perturbation is
        // the domain input, not auto-derivable. Round-trip + capability are.
        capability_matches_residual::<Round>();
    }

    #[test]
    fn scale_is_probed() {
        // A Pure, lossless transport: round-trip + the Pure => Unit-residual law.
        morphism_round_trips(&Scale::honest(), quantity());
        capability_matches_residual::<Scale>();
    }

    #[test]
    fn parse_cents_is_probed() {
        construction_round_trips(&ParseCents, cents_raw());
        construction_capability_matches_residual::<ParseCents>();
    }

    #[test]
    fn parse_account_is_probed() {
        construction_round_trips(&ParseAccount, account_raw());
        construction_residual_complete(&ParseAccount, &PadName, account_raw());
        construction_capability_matches_residual::<ParseAccount>();
    }

    #[test]
    fn parse_transaction_is_probed() {
        construction_round_trips(&ParseTransaction, postings(1));
        construction_residual_complete(&ParseTransaction, &ReorderPostings, postings(2));
        construction_capability_matches_residual::<ParseTransaction>();
    }
}
