//! laws — AUTOGENERATED probing: an edge's laws are DERIVED from its trait, not
//! hand-written per edge. This is how the category pays for itself — repeatable
//! testing without writing tests.
//!
//! Being a `Morphism` ENTAILS the residual round-trip (`backward . forward == id`)
//! and the capability law (`Pure => Unit residual`); being a `Construction` entails
//! the parse round-trip (`reconstruct . parse == id`); registering a `Perturbation`
//! entails the completeness probe. So a NEW edge gets its whole structural suite by
//! REGISTERING it in `registry` below — and, because each input type supplies its own
//! generator via `Sampled`, the round-trip and capability laws take NO argument at
//! all: `morphism_laws(&Aggregate);` is the entire registration. The harnesses are
//! generic over the trait, so they apply to every present and future edge uniformly,
//! and this `registry` SUBSUMES the per-edge round-trip/completeness demos that used
//! to live in `properties.rs`/`tests.rs`.
//!
//! Division of labour: these are the STRUCTURAL laws that follow from the algebra; the
//! DOMAIN laws that don't (commutativity, involution, the quantitative coefficient)
//! and the NEGATIVE tests (a probe CATCHING a planted bug) stay hand-written.
//! cargo-mutants then certifies these derived laws are strong and surfaces any degree
//! of freedom a generated suite still misses (the `select`/`synth` loop).

use core::any::TypeId;

use proptest::prelude::*;
use proptest::strategy::BoxedStrategy;
use proptest::test_runner::TestRunner;

use crate::boundary::{
    construction_probe, probe, reconstructs, run, Capability, Construction, Morphism, Perturbation,
    RawPerturbation, Unit,
};

// ===== Sampled: a type supplies its OWN canonical input distribution =======

/// A canonical distribution of VALID inputs for a type, built through its own
/// constructor — so a law harness needs no per-edge strategy argument: the input type
/// supplies its generator. "Valid" means *admitted* (a parse accepts it, an operator's
/// precondition holds), so the derived round-trip law is meaningful.
pub trait Sampled: Sized + core::fmt::Debug {
    fn sampled() -> BoxedStrategy<Self>;
}

// ===== the generic law harnesses (derived from the traits) ===============

/// LAW (every `Morphism`): with its residual retained, `backward . forward == id`
/// for every generated input. Derived purely from `Morphism` — no per-edge assertion.
pub fn morphism_round_trips<M, S>(m: &M, strategy: S)
where
    M: Morphism,
    S: Strategy<Value = M::In>,
{
    TestRunner::default()
        .run(&strategy, |x| {
            let carried = run(m, &x);
            let recovered = carried.invert(m);
            prop_assert_eq!(recovered.as_ref(), Some(&x));
            Ok(())
        })
        .unwrap();
}

/// LAW (a `Morphism` + a `Perturbation` of a lossy dimension): the residual is
/// COMPLETE on every generated input — output invariant, residual responds, the
/// perturbed input round-trips.
pub fn morphism_residual_complete<M, P, S>(m: &M, p: &P, strategy: S)
where
    M: Morphism,
    P: Perturbation<M>,
    S: Strategy<Value = M::In>,
{
    TestRunner::default()
        .run(&strategy, |x| {
            let pr = probe(m, p, &x).expect("the perturbation applies on this strategy");
            prop_assert!(pr.residual_complete(), "incomplete residual at {:?}", x);
            Ok(())
        })
        .unwrap();
}

/// LAW (every `Construction`): an admitted raw reconstructs EXACTLY —
/// `reconstruct . parse == id` for every generated raw.
pub fn construction_round_trips<C, S>(c: &C, strategy: S)
where
    C: Construction,
    S: Strategy<Value = C::Raw>,
{
    TestRunner::default()
        .run(&strategy, |raw| {
            prop_assert_eq!(
                reconstructs(c, &raw),
                Some(true),
                "no round-trip at {:?}",
                raw
            );
            Ok(())
        })
        .unwrap();
}

/// LAW (a `Construction` + a `RawPerturbation`): the residual is COMPLETE on every
/// generated raw — the entry-edge analog of `morphism_residual_complete`.
pub fn construction_residual_complete<C, P, S>(c: &C, p: &P, strategy: S)
where
    C: Construction,
    P: RawPerturbation<C>,
    S: Strategy<Value = C::Raw>,
{
    TestRunner::default()
        .run(&strategy, |raw| {
            let pr = construction_probe(c, p, &raw).expect("the perturbation applies");
            prop_assert!(pr.residual_complete(), "incomplete residual at {:?}", raw);
            Ok(())
        })
        .unwrap();
}

/// LAW (every `Morphism`): a `Pure` edge loses nothing, so its residual MUST be
/// `Unit`. A static, input-free consistency check between the declared capability and
/// the residual type — it catches a `Pure` declared on a lossy map.
pub fn capability_matches_residual<M: Morphism>()
where
    M::Residual: 'static,
{
    let residual_is_unit = TypeId::of::<M::Residual>() == TypeId::of::<Unit>();
    if M::CAPABILITY == Capability::Pure {
        assert!(
            residual_is_unit,
            "a Pure morphism must have a Unit residual (it loses nothing)"
        );
    }
}

/// The construction analog of `capability_matches_residual`.
pub fn construction_capability_matches_residual<C: Construction>()
where
    C::Residual: 'static,
{
    let residual_is_unit = TypeId::of::<C::Residual>() == TypeId::of::<Unit>();
    if C::CAPABILITY == Capability::Pure {
        assert!(
            residual_is_unit,
            "a Pure construction must have a Unit residual (it loses nothing)"
        );
    }
}

// ===== argument-free registration: the laws a TYPE already entails =========

/// Every structural law a `Morphism` entails, with the input drawn from `Sampled` —
/// so registering an edge is one argument-free call.
pub fn morphism_laws<M>(m: &M)
where
    M: Morphism,
    M::In: Sampled + 'static,
    M::Residual: 'static,
{
    morphism_round_trips(m, M::In::sampled());
    capability_matches_residual::<M>();
}

/// Every structural law a `Construction` entails, input drawn from `Sampled`.
pub fn construction_laws<C>(c: &C)
where
    C: Construction,
    C::Raw: Sampled + 'static,
    C::Residual: 'static,
{
    construction_round_trips(c, C::Raw::sampled());
    construction_capability_matches_residual::<C>();
}

// ===== the input distributions, each built through a smart constructor =====

#[cfg(test)]
use crate::ledger::boundary::{Account, AccountSummary, Aggregate, Cents, Posting, Transaction};
#[cfg(test)]
use crate::lifecycle::boundary::{Draft, Entry};
#[cfg(test)]
use crate::linear::boundary::Quantity;

#[cfg(test)]
fn account_raw() -> impl Strategy<Value = String> {
    (
        prop_oneof![Just(""), Just(" "), Just("  "), Just("\t")],
        prop_oneof![Just("Cash"), Just("Revenue"), Just("Tax"), Just("Fees")],
        prop_oneof![Just(""), Just(" "), Just("  ")],
    )
        .prop_map(|(lead, name, trail)| format!("{lead}{name}{trail}"))
}

#[cfg(test)]
fn posting(amount: impl Strategy<Value = i64>) -> impl Strategy<Value = Posting> {
    (
        prop_oneof![Just("Cash"), Just("Revenue"), Just("Tax"), Just("Fees")],
        amount,
    )
        .prop_map(|(a, m)| Posting::new(Account::new(a).unwrap(), Cents::new(m).unwrap()))
}

#[cfg(test)]
fn postings(min: usize) -> impl Strategy<Value = Vec<Posting>> {
    prop::collection::vec(posting(-1_000_000i64..=1_000_000), min..=8)
}

#[cfg(test)]
fn transaction() -> impl Strategy<Value = Transaction> {
    postings(1).prop_map(|p| Transaction::new(p).unwrap())
}

/// Substantial amounts so the `Split` perturbation actually moves multiplicity.
#[cfg(test)]
fn tx_substantial() -> impl Strategy<Value = Transaction> {
    prop::collection::vec(
        posting(prop_oneof![1_000i64..=1_000_000, -1_000_000i64..=-1_000]),
        2..=8,
    )
    .prop_map(|p| Transaction::new(p).unwrap())
}

#[cfg(test)]
impl Sampled for i64 {
    fn sampled() -> BoxedStrategy<Self> {
        (-100_000_000i64..=100_000_000).boxed() // the valid `Cents` range
    }
}
#[cfg(test)]
impl Sampled for String {
    fn sampled() -> BoxedStrategy<Self> {
        account_raw().boxed()
    }
}
#[cfg(test)]
impl Sampled for Vec<Posting> {
    fn sampled() -> BoxedStrategy<Self> {
        postings(1).boxed()
    }
}
#[cfg(test)]
impl Sampled for Transaction {
    fn sampled() -> BoxedStrategy<Self> {
        transaction().boxed()
    }
}
#[cfg(test)]
impl Sampled for AccountSummary {
    fn sampled() -> BoxedStrategy<Self> {
        transaction().prop_map(|t| Aggregate.forward(&t).0).boxed()
    }
}
#[cfg(test)]
impl Sampled for Quantity {
    fn sampled() -> BoxedStrategy<Self> {
        (-50_000i64..=50_000)
            .prop_map(|n| Quantity::new(n).unwrap())
            .boxed()
    }
}
#[cfg(test)]
impl Sampled for Entry<Draft> {
    fn sampled() -> BoxedStrategy<Self> {
        transaction().prop_map(Entry::<Draft>::draft).boxed()
    }
}

// ===== the registry: register an edge; the laws are automatic =============

#[cfg(test)]
mod registry {
    use super::*;
    use crate::boundary::Compose;
    use crate::ledger::boundary::{
        PadName, ParseAccount, ParseCents, ParseTransaction, ReorderPostings, Round, Split,
    };
    use crate::lifecycle::boundary::Submit;
    use crate::linear::boundary::Scale;

    // Each edge: ONE registration. Round-trip + capability are argument-free
    // (`Sampled` supplies the input); completeness adds its matched perturbation.

    #[test]
    fn aggregate_is_probed() {
        morphism_laws(&Aggregate);
        morphism_residual_complete(&Aggregate, &Split, tx_substantial());
    }

    #[test]
    fn round_is_probed() {
        // Completeness needs a perturbation matched to the lost dimension; a bare +1c
        // can cross a dollar boundary, so it is NOT complete over arbitrary summaries.
        // Round-trip + capability are.
        morphism_laws(&Round);
    }

    #[test]
    fn scale_is_probed() {
        morphism_laws(&Scale::honest());
        morphism_laws(&Scale::skew()); // a wrong coefficient still round-trips
    }

    #[test]
    fn compose_is_probed() {
        morphism_laws(&Compose {
            f: Aggregate,
            g: Round,
        });
    }

    #[test]
    fn submit_transition_is_probed() {
        morphism_laws(&Submit); // a reversible typestate transition is just a Morphism
    }

    #[test]
    fn parse_cents_is_probed() {
        construction_laws(&ParseCents);
    }

    #[test]
    fn parse_account_is_probed() {
        construction_laws(&ParseAccount);
        construction_residual_complete(&ParseAccount, &PadName, account_raw());
    }

    #[test]
    fn parse_transaction_is_probed() {
        construction_laws(&ParseTransaction);
        construction_residual_complete(&ParseTransaction, &ReorderPostings, postings(2));
    }
}
