//! `gauge`'s strict value-object surface — a DOOR by structure: its operator methods
//! front the interior workshop, which derives this file BOUNDARY (the tier-1 grammar).
//!
//! GENERATED by genesis from the `relay-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! The newtypes below are STRUCTURE; their validity rules are carried VERBATIM from the
//! declaration as meaning holes. Operator methods delegate inward — the tier-1 grammar
//! (no free functions, no public fields, no I/O) is enforced by this crate's build.rs.

use crate::mixer::Level;

// ===== operator methods — mechanical delegation; the meaning lives in the
// interior workshop =====

impl Level {
    /// `fuse` — declared `fuse(Level, Level) -> Level`, delegated to the interior
    /// (`crate::gauge_internal::fuse`), where its MEANING hole lives.
    ///
    /// Declared expectations (the target lock restates them): commutative(fuse).
    pub fn fuse(self, b: Level) -> Level {
        crate::gauge_internal::fuse(self, b)
    }
}
