//! The workshop `gauge`'s boundary delegates to — not pub-reachable, deriving INTERIOR
//! (the tier-2 inward rule holds: nothing here returns a raw primitive).
//!
//! GENERATED by genesis from the `relay-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! Every body below is THE meaning hole for its operator. The interior is free — raw
//! representation arithmetic, any style — but the only way back out is a value object's
//! `mint`, so a quantity cannot leave un-validated.

use crate::mixer::Level;

/// `fuse` — the operator's interior.
/// Declared expectations to honour (discovery must re-earn them): commutative(fuse).
pub(crate) fn fuse(a: Level, b: Level) -> Level {
    // MEANING (filled): fusing gauge readings keeps the higher level — the target-side
    // twin of `blend`, which is what lets the seam's conversion carry one into the other.
    Level::mint(a.get().max(b.get()))
}
