//! `mixer`'s strict value-object surface — a DOOR by structure: its operator methods
//! front the interior workshop, which derives this file BOUNDARY (the tier-1 grammar).
//!
//! GENERATED by genesis from the `relay-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! The newtypes below are STRUCTURE; their validity rules are carried VERBATIM from the
//! declaration as meaning holes. Operator methods delegate inward — the tier-1 grammar
//! (no free functions, no public fields, no I/O) is enforced by this crate's build.rs.

use boundary_spec::boundary::Shaped;

/// `Signal` — `i64` refined by a declared validity rule.
///
/// VALIDITY (declared, structured — the implied artifacts below are generated): "-8..=8 (saturating)"
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Signal(i64);

impl Signal {
    /// Parse, don't validate: `Some` iff `raw` satisfies the declared rule.
    pub fn new(raw: i64) -> Option<Signal> {
        // GENERATED from the declared rule `-8..=8 (saturating)` — a structured rule is
        // tokens, so its predicate is derived, never re-transcribed by hand.
        (-8..=8).contains(&raw).then_some(Signal(raw))
    }

    /// The raw value — the sanctioned exit hatch.
    #[allow(clippy::clone_on_copy)] // the generic form: raw may or may not be Copy
    pub fn get(&self) -> i64 {
        self.0.clone()
    }

    /// The interior's way back into validity — the DECLARED re-entry policy:
    /// a computation may overshoot either edge of `-8..=8 (saturating)`; the value saturates.
    pub(crate) fn mint(raw: i64) -> Signal {
        Signal(raw.clamp(-8, 8))
    }
}

/// The probe/grid surface — GENERATED from the declared range: the grid seeds at the
/// lower edge and steps toward BOTH edges, so discovery judges laws at the rule's
/// load-bearing points (the closure reaches the entire range, cap permitting).
impl Shaped for Signal {
    fn inhabitant() -> Self {
        Signal(-8)
    }
    fn perturbation_classes(&self) -> Vec<Vec<Self>> {
        vec![
            vec![Signal(self.0.saturating_add(1).clamp(-8, 8)), Signal(8)],
            vec![Signal(self.0.saturating_sub(1).clamp(-8, 8)), Signal(-8)],
        ]
    }
}

/// `Level` — `i64` refined by a declared validity rule.
///
/// VALIDITY (declared, structured — the implied artifacts below are generated): "0..=16 (saturating)"
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Level(i64);

impl Level {
    /// Parse, don't validate: `Some` iff `raw` satisfies the declared rule.
    pub fn new(raw: i64) -> Option<Level> {
        // GENERATED from the declared rule `0..=16 (saturating)` — a structured rule is
        // tokens, so its predicate is derived, never re-transcribed by hand.
        (0..=16).contains(&raw).then_some(Level(raw))
    }

    /// The raw value — the sanctioned exit hatch.
    #[allow(clippy::clone_on_copy)] // the generic form: raw may or may not be Copy
    pub fn get(&self) -> i64 {
        self.0.clone()
    }

    /// The interior's way back into validity — the DECLARED re-entry policy:
    /// a computation may overshoot either edge of `0..=16 (saturating)`; the value saturates.
    pub(crate) fn mint(raw: i64) -> Level {
        Level(raw.clamp(0, 16))
    }
}

/// The probe/grid surface — GENERATED from the declared range: the grid seeds at the
/// lower edge and steps toward BOTH edges, so discovery judges laws at the rule's
/// load-bearing points (the closure reaches the entire range, cap permitting).
impl Shaped for Level {
    fn inhabitant() -> Self {
        Level(0)
    }
    fn perturbation_classes(&self) -> Vec<Vec<Self>> {
        vec![
            vec![Level(self.0.saturating_add(1).clamp(0, 16)), Level(16)],
            vec![Level(self.0.saturating_sub(1).clamp(0, 16)), Level(0)],
        ]
    }
}

boundary_spec::value_object!(Signal, Level);

// ===== operator methods — mechanical delegation; the meaning lives in the
// interior workshop =====

impl Signal {
    /// `blend` — declared `blend(Signal, Signal) -> Signal`, delegated to the interior
    /// (`crate::mixer_internal::blend`), where its MEANING hole lives.
    ///
    /// Declared expectations (the target lock restates them): commutative(blend); idempotent(blend).
    pub fn blend(self, b: Signal) -> Signal {
        crate::mixer_internal::blend(self, b)
    }

    /// `cook` — declared `cook(Signal) -> Level`, delegated to the interior
    /// (`crate::mixer_internal::cook`), where its MEANING hole lives.
    pub fn cook(self) -> Level {
        crate::mixer_internal::cook(self)
    }
}
