//! Tier: INTERIOR — the workshop `mixer`'s boundary delegates to (the tier-2 inward
//! rule holds: nothing here returns a raw primitive).
//!
//! GENERATED by genesis from the `relay-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! Every body below is THE meaning hole for its operator. The interior is free — raw
//! representation arithmetic, any style — but the only way back out is a value object's
//! `mint`, so a quantity cannot leave un-validated.

use crate::mixer::Level;
use crate::mixer::Signal;

/// `blend` — the operator's interior.
/// Declared expectations to honour (discovery must re-earn them): commutative(blend); idempotent(blend).
pub(crate) fn blend(a: Signal, b: Signal) -> Signal {
    // MEANING (filled): blending keeps the STRONGER signal — max is symmetric (the declared
    // commutativity) and a signal blended with itself is itself (the declared idempotence).
    Signal::mint(a.get().max(b.get()))
}

/// `cook` — the operator's interior.
/// No laws were declared for it — whatever discovery finds is the spec.
pub(crate) fn cook(a: Signal) -> Level {
    // MEANING (filled): cooking re-bases a signed signal onto the unsigned gauge scale — a
    // monotone shift, so the stronger signal cooks to the higher level: exactly the
    // homomorphism the seam declares (cook(blend(x, y)) = fuse(cook(x), cook(y))).
    Level::mint(a.get() + 8)
}
