//! Tier: ALGEBRA — the discovered-law layer: each declared module's operators, as the
//! theory `#[algebra]` synthesises from ordinary function signatures.
//!
//! GENERATED by genesis from the `relay-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! Nothing about the algebras is asserted here. The `expects(...)` attribute argument
//! carries the DECLARED expectations through AS WRITTEN in the declaration; discovery
//! must re-earn them by running these functions, and the committed `spec/*.spec` target
//! locks stay red until it does.

use boundary_spec::algebra;

/// `mixer`'s operator surface for discovery: the theory (`Mixer`, named "mixer") is what
/// `#[algebra]` reads off the signatures below.
#[algebra(Mixer, "mixer", expects(commutative(blend), idempotent(blend)))]
pub mod mixer_ops {
    pub use crate::mixer::Level;
    pub use crate::mixer::Signal;

    /// `blend` — mechanical delegation to the boundary surface.
    pub fn blend(a: Signal, b: Signal) -> Signal {
        a.blend(b)
    }

    /// `cook` — mechanical delegation to the boundary surface.
    pub fn cook(a: Signal) -> Level {
        a.cook()
    }
}

/// `gauge`'s operator surface for discovery: the theory (`Gauge`, named "gauge") is what
/// `#[algebra]` reads off the signatures below.
#[algebra(Gauge, "gauge", expects(commutative(fuse)))]
pub mod gauge_ops {
    pub use crate::mixer::Level;

    /// `fuse` — mechanical delegation to the boundary surface.
    pub fn fuse(a: Level, b: Level) -> Level {
        a.fuse(b)
    }
}

/// The SPANNING theory for the `mixer -- gauge` transform seam: source operator, conversion, and
/// target operator in one table — the homomorphism expectation rides the attribute, and the
/// compiled seam (`src/system.rs`) holds discovery to it.
#[algebra(
    MixerGaugeSeam,
    "mixer-gauge seam",
    expects(homomorphism(cook, blend, fuse))
)]
pub mod mixer_gauge_seam_ops {
    pub use crate::mixer::Level;
    pub use crate::mixer::Signal;

    /// `blend` — the source-side operator, delegated to the boundary surface.
    pub fn blend(a: Signal, b: Signal) -> Signal {
        a.blend(b)
    }

    /// `cook` — the crossing conversion, delegated to the boundary surface.
    pub fn cook(a: Signal) -> Level {
        a.cook()
    }

    /// `fuse` — the target-side operator, delegated to the boundary surface.
    pub fn fuse(a: Level, b: Level) -> Level {
        a.fuse(b)
    }
}
