//! Tier: ALGEBRA — the compiled `system!` graph: the application-level spec as a checked artifact.
//!
//! GENERATED by genesis from the `relay-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! The graph IS the registry: `modules()` is the list the freeze loop records and the
//! drift gate checks (a module cannot silently fall out of it), and the rendered graph
//! — modules, seams, each seam's obligation and status — freezes into the committed
//! `spec/*.system.spec` lock. Declared transport seams are discharged BY CONSTRUCTION:
//! each shared value object is defined exactly once, and the `system!` macro emits the
//! compile-time witness that keeps that true.

use crate::ops::gauge_ops::Gauge;
use crate::ops::mixer_gauge_seam_ops::MixerGaugeSeam;
use crate::ops::mixer_ops::Mixer;

/// The system marker — `SystemReport::of::<RelayApp>()` is the graph the lock freezes.
pub struct RelayApp;

boundary_spec::system! {
    RelayApp : "relay-app",
    modules {
        Mixer;
        Gauge;
    }
    seams {
        Mixer -- Gauge : transform on Signal via cook in MixerGaugeSeam;
    }
}
