//! Tier: ALGEBRA — the compiled `system!` graph: ONE declaration, two lifecycle stages.
//!
//! GENERATED by genesis from the `relay-app` system declaration. STRUCTURE here is derived
//! and regenerable; MEANING is not — every hole is a loud `todo!("MEANING: …")`.
//! Grep `MEANING:` for the complete list of what a human/agent still owes this crate.
//!
//! The block below is the ORIGINAL system declaration, spliced VERBATIM — the same
//! tokens genesis derived this whole crate from, now COMPILING: `modules()` (the
//! registry the freeze loop reads) resolves each module name to its theory, every
//! declared operator signature is a compile-time witness against the code, and the
//! seams wire to their checkers. Edit the declaration HERE and the crate follows or
//! fails to build — the declaration cannot go stale.

/// The system marker — `SystemReport::of::<RelayApp>()` is the graph the lock freezes.
pub struct RelayApp;

boundary_spec::system! {
    RelayApp:
    name: "relay-app",
    values {
        Signal = i64 where -8..=8 saturating;
        Level = i64 where 0..=16 saturating;
    }
    modules {
        mixer {
            ops {
                blend(Signal, Signal) -> Signal;
                cook(Signal) -> Level;
            }
            expects {
                commutative(blend);
                idempotent(blend);
            }
        }
        gauge {
            ops {
                fuse(Level, Level) -> Level;
            }
            expects {
                commutative(fuse);
            }
        }
    }
    seams {
        mixer -- gauge : transform on Signal via cook;
    }
}
